#pragma once

// Ranges Unicode FontAwesome 6
#define FA_MIN_CODEPOINT 0xe005
#define FA_MAX_CODEPOINT 0xf8ff

// Ranges Unicode Codicon
#define CODICON_MIN_CODEPOINT 0xea60
#define CODICON_MAX_CODEPOINT 0xebeb

// Common macros for icons
#pragma region Font Awesome

// https://github.com/juliettef/IconFontCppHeaders/blob/main/IconsFontAwesome4.h

#define ICON_FA_GLASS "\xef\x80\x80"	// U+f000
#define ICON_FA_MUSIC "\xef\x80\x81"	// U+f001
#define ICON_FA_SEARCH "\xef\x80\x82"	// U+f002
#define ICON_FA_ENVELOPE_O "\xef\x80\x83"	// U+f003
#define ICON_FA_HEART "\xef\x80\x84"	// U+f004
#define ICON_FA_STAR "\xef\x80\x85"	// U+f005
#define ICON_FA_STAR_O "\xef\x80\x86"	// U+f006
#define ICON_FA_USER "\xef\x80\x87"	// U+f007
#define ICON_FA_FILM "\xef\x80\x88"	// U+f008
#define ICON_FA_TH_LARGE "\xef\x80\x89"	// U+f009
#define ICON_FA_TH "\xef\x80\x8a"	// U+f00a
#define ICON_FA_TH_LIST "\xef\x80\x8b"	// U+f00b
#define ICON_FA_CHECK "\xef\x80\x8c"	// U+f00c
#define ICON_FA_TIMES "\xef\x80\x8d"	// U+f00d
#define ICON_FA_SEARCH_PLUS "\xef\x80\x8e"	// U+f00e
#define ICON_FA_SEARCH_MINUS "\xef\x80\x90"	// U+f010
#define ICON_FA_POWER_OFF "\xef\x80\x91"	// U+f011
#define ICON_FA_SIGNAL "\xef\x80\x92"	// U+f012
#define ICON_FA_COG "\xef\x80\x93"	// U+f013
#define ICON_FA_TRASH_O "\xef\x80\x94"	// U+f014
#define ICON_FA_HOME "\xef\x80\x95"	// U+f015
#define ICON_FA_FILE_O "\xef\x80\x96"	// U+f016
#define ICON_FA_CLOCK_O "\xef\x80\x97"	// U+f017
#define ICON_FA_ROAD "\xef\x80\x98"	// U+f018
#define ICON_FA_DOWNLOAD "\xef\x80\x99"	// U+f019
#define ICON_FA_ARROW_CIRCLE_O_DOWN "\xef\x80\x9a"	// U+f01a
#define ICON_FA_ARROW_CIRCLE_O_UP "\xef\x80\x9b"	// U+f01b
#define ICON_FA_INBOX "\xef\x80\x9c"	// U+f01c
#define ICON_FA_PLAY_CIRCLE_O "\xef\x80\x9d"	// U+f01d
#define ICON_FA_REPEAT "\xef\x80\x9e"	// U+f01e
#define ICON_FA_REFRESH "\xef\x80\xa1"	// U+f021
#define ICON_FA_LIST_ALT "\xef\x80\xa2"	// U+f022
#define ICON_FA_LOCK "\xef\x80\xa3"	// U+f023
#define ICON_FA_FLAG "\xef\x80\xa4"	// U+f024
#define ICON_FA_HEADPHONES "\xef\x80\xa5"	// U+f025
#define ICON_FA_VOLUME_OFF "\xef\x80\xa6"	// U+f026
#define ICON_FA_VOLUME_DOWN "\xef\x80\xa7"	// U+f027
#define ICON_FA_VOLUME_UP "\xef\x80\xa8"	// U+f028
#define ICON_FA_QRCODE "\xef\x80\xa9"	// U+f029
#define ICON_FA_BARCODE "\xef\x80\xaa"	// U+f02a
#define ICON_FA_TAG "\xef\x80\xab"	// U+f02b
#define ICON_FA_TAGS "\xef\x80\xac"	// U+f02c
#define ICON_FA_BOOK "\xef\x80\xad"	// U+f02d
#define ICON_FA_BOOKMARK "\xef\x80\xae"	// U+f02e
#define ICON_FA_PRINT "\xef\x80\xaf"	// U+f02f
#define ICON_FA_CAMERA "\xef\x80\xb0"	// U+f030
#define ICON_FA_FONT "\xef\x80\xb1"	// U+f031
#define ICON_FA_BOLD "\xef\x80\xb2"	// U+f032
#define ICON_FA_ITALIC "\xef\x80\xb3"	// U+f033
#define ICON_FA_TEXT_HEIGHT "\xef\x80\xb4"	// U+f034
#define ICON_FA_TEXT_WIDTH "\xef\x80\xb5"	// U+f035
#define ICON_FA_ALIGN_LEFT "\xef\x80\xb6"	// U+f036
#define ICON_FA_ALIGN_CENTER "\xef\x80\xb7"	// U+f037
#define ICON_FA_ALIGN_RIGHT "\xef\x80\xb8"	// U+f038
#define ICON_FA_ALIGN_JUSTIFY "\xef\x80\xb9"	// U+f039
#define ICON_FA_LIST "\xef\x80\xba"	// U+f03a
#define ICON_FA_OUTDENT "\xef\x80\xbb"	// U+f03b
#define ICON_FA_INDENT "\xef\x80\xbc"	// U+f03c
#define ICON_FA_VIDEO_CAMERA "\xef\x80\xbd"	// U+f03d
#define ICON_FA_PICTURE_O "\xef\x80\xbe"	// U+f03e
#define ICON_FA_PENCIL "\xef\x81\x80"	// U+f040
#define ICON_FA_MAP_MARKER "\xef\x81\x81"	// U+f041
#define ICON_FA_ADJUST "\xef\x81\x82"	// U+f042
#define ICON_FA_TINT "\xef\x81\x83"	// U+f043
#define ICON_FA_PENCIL_SQUARE_O "\xef\x81\x84"	// U+f044
#define ICON_FA_SHARE_SQUARE_O "\xef\x81\x85"	// U+f045
#define ICON_FA_CHECK_SQUARE_O "\xef\x81\x86"	// U+f046
#define ICON_FA_ARROWS "\xef\x81\x87"	// U+f047
#define ICON_FA_STEP_BACKWARD "\xef\x81\x88"	// U+f048
#define ICON_FA_FAST_BACKWARD "\xef\x81\x89"	// U+f049
#define ICON_FA_BACKWARD "\xef\x81\x8a"	// U+f04a
#define ICON_FA_PLAY "\xef\x81\x8b"	// U+f04b
#define ICON_FA_PAUSE "\xef\x81\x8c"	// U+f04c
#define ICON_FA_STOP "\xef\x81\x8d"	// U+f04d
#define ICON_FA_FORWARD "\xef\x81\x8e"	// U+f04e
#define ICON_FA_FAST_FORWARD "\xef\x81\x90"	// U+f050
#define ICON_FA_STEP_FORWARD "\xef\x81\x91"	// U+f051
#define ICON_FA_EJECT "\xef\x81\x92"	// U+f052
#define ICON_FA_CHEVRON_LEFT "\xef\x81\x93"	// U+f053
#define ICON_FA_CHEVRON_RIGHT "\xef\x81\x94"	// U+f054
#define ICON_FA_PLUS_CIRCLE "\xef\x81\x95"	// U+f055
#define ICON_FA_MINUS_CIRCLE "\xef\x81\x96"	// U+f056
#define ICON_FA_TIMES_CIRCLE "\xef\x81\x97"	// U+f057
#define ICON_FA_CHECK_CIRCLE "\xef\x81\x98"	// U+f058
#define ICON_FA_QUESTION_CIRCLE "\xef\x81\x99"	// U+f059
#define ICON_FA_INFO_CIRCLE "\xef\x81\x9a"	// U+f05a
#define ICON_FA_CROSSHAIRS "\xef\x81\x9b"	// U+f05b
#define ICON_FA_TIMES_CIRCLE_O "\xef\x81\x9c"	// U+f05c
#define ICON_FA_CHECK_CIRCLE_O "\xef\x81\x9d"	// U+f05d
#define ICON_FA_BAN "\xef\x81\x9e"	// U+f05e
#define ICON_FA_ARROW_LEFT "\xef\x81\xa0"	// U+f060
#define ICON_FA_ARROW_RIGHT "\xef\x81\xa1"	// U+f061
#define ICON_FA_ARROW_UP "\xef\x81\xa2"	// U+f062
#define ICON_FA_ARROW_DOWN "\xef\x81\xa3"	// U+f063
#define ICON_FA_SHARE "\xef\x81\xa4"	// U+f064
#define ICON_FA_EXPAND "\xef\x81\xa5"	// U+f065
#define ICON_FA_COMPRESS "\xef\x81\xa6"	// U+f066
#define ICON_FA_PLUS "\xef\x81\xa7"	// U+f067
#define ICON_FA_MINUS "\xef\x81\xa8"	// U+f068
#define ICON_FA_ASTERISK "\xef\x81\xa9"	// U+f069
#define ICON_FA_EXCLAMATION_CIRCLE "\xef\x81\xaa"	// U+f06a
#define ICON_FA_GIFT "\xef\x81\xab"	// U+f06b
#define ICON_FA_LEAF "\xef\x81\xac"	// U+f06c
#define ICON_FA_FIRE "\xef\x81\xad"	// U+f06d
#define ICON_FA_EYE "\xef\x81\xae"	// U+f06e
#define ICON_FA_EYE_SLASH "\xef\x81\xb0"	// U+f070
#define ICON_FA_EXCLAMATION_TRIANGLE "\xef\x81\xb1"	// U+f071
#define ICON_FA_PLANE "\xef\x81\xb2"	// U+f072
#define ICON_FA_CALENDAR "\xef\x81\xb3"	// U+f073
#define ICON_FA_RANDOM "\xef\x81\xb4"	// U+f074
#define ICON_FA_COMMENT "\xef\x81\xb5"	// U+f075
#define ICON_FA_MAGNET "\xef\x81\xb6"	// U+f076
#define ICON_FA_CHEVRON_UP "\xef\x81\xb7"	// U+f077
#define ICON_FA_CHEVRON_DOWN "\xef\x81\xb8"	// U+f078
#define ICON_FA_RETWEET "\xef\x81\xb9"	// U+f079
#define ICON_FA_SHOPPING_CART "\xef\x81\xba"	// U+f07a
#define ICON_FA_FOLDER "\xef\x81\xbb"	// U+f07b
#define ICON_FA_FOLDER_OPEN "\xef\x81\xbc"	// U+f07c
#define ICON_FA_ARROWS_V "\xef\x81\xbd"	// U+f07d
#define ICON_FA_ARROWS_H "\xef\x81\xbe"	// U+f07e
#define ICON_FA_BAR_CHART "\xef\x82\x80"	// U+f080
#define ICON_FA_TWITTER_SQUARE "\xef\x82\x81"	// U+f081
#define ICON_FA_FACEBOOK_SQUARE "\xef\x82\x82"	// U+f082
#define ICON_FA_CAMERA_RETRO "\xef\x82\x83"	// U+f083
#define ICON_FA_KEY "\xef\x82\x84"	// U+f084
#define ICON_FA_COGS "\xef\x82\x85"	// U+f085
#define ICON_FA_COMMENTS "\xef\x82\x86"	// U+f086
#define ICON_FA_THUMBS_O_UP "\xef\x82\x87"	// U+f087
#define ICON_FA_THUMBS_O_DOWN "\xef\x82\x88"	// U+f088
#define ICON_FA_STAR_HALF "\xef\x82\x89"	// U+f089
#define ICON_FA_HEART_O "\xef\x82\x8a"	// U+f08a
#define ICON_FA_SIGN_OUT "\xef\x82\x8b"	// U+f08b
#define ICON_FA_LINKEDIN_SQUARE "\xef\x82\x8c"	// U+f08c
#define ICON_FA_THUMB_TACK "\xef\x82\x8d"	// U+f08d
#define ICON_FA_EXTERNAL_LINK "\xef\x82\x8e"	// U+f08e
#define ICON_FA_SIGN_IN "\xef\x82\x90"	// U+f090
#define ICON_FA_TROPHY "\xef\x82\x91"	// U+f091
#define ICON_FA_GITHUB_SQUARE "\xef\x82\x92"	// U+f092
#define ICON_FA_UPLOAD "\xef\x82\x93"	// U+f093
#define ICON_FA_LEMON_O "\xef\x82\x94"	// U+f094
#define ICON_FA_PHONE "\xef\x82\x95"	// U+f095
#define ICON_FA_SQUARE_O "\xef\x82\x96"	// U+f096
#define ICON_FA_BOOKMARK_O "\xef\x82\x97"	// U+f097
#define ICON_FA_PHONE_SQUARE "\xef\x82\x98"	// U+f098
#define ICON_FA_TWITTER "\xef\x82\x99"	// U+f099
#define ICON_FA_FACEBOOK "\xef\x82\x9a"	// U+f09a
#define ICON_FA_GITHUB "\xef\x82\x9b"	// U+f09b
#define ICON_FA_UNLOCK "\xef\x82\x9c"	// U+f09c
#define ICON_FA_CREDIT_CARD "\xef\x82\x9d"	// U+f09d
#define ICON_FA_RSS "\xef\x82\x9e"	// U+f09e
#define ICON_FA_HDD_O "\xef\x82\xa0"	// U+f0a0
#define ICON_FA_BULLHORN "\xef\x82\xa1"	// U+f0a1
#define ICON_FA_BELL "\xef\x83\xb3"	// U+f0f3
#define ICON_FA_CERTIFICATE "\xef\x82\xa3"	// U+f0a3
#define ICON_FA_HAND_O_RIGHT "\xef\x82\xa4"	// U+f0a4
#define ICON_FA_HAND_O_LEFT "\xef\x82\xa5"	// U+f0a5
#define ICON_FA_HAND_O_UP "\xef\x82\xa6"	// U+f0a6
#define ICON_FA_HAND_O_DOWN "\xef\x82\xa7"	// U+f0a7
#define ICON_FA_ARROW_CIRCLE_LEFT "\xef\x82\xa8"	// U+f0a8
#define ICON_FA_ARROW_CIRCLE_RIGHT "\xef\x82\xa9"	// U+f0a9
#define ICON_FA_ARROW_CIRCLE_UP "\xef\x82\xaa"	// U+f0aa
#define ICON_FA_ARROW_CIRCLE_DOWN "\xef\x82\xab"	// U+f0ab
#define ICON_FA_GLOBE "\xef\x82\xac"	// U+f0ac
#define ICON_FA_WRENCH "\xef\x82\xad"	// U+f0ad
#define ICON_FA_TASKS "\xef\x82\xae"	// U+f0ae
#define ICON_FA_FILTER "\xef\x82\xb0"	// U+f0b0
#define ICON_FA_BRIEFCASE "\xef\x82\xb1"	// U+f0b1
#define ICON_FA_ARROWS_ALT "\xef\x82\xb2"	// U+f0b2
#define ICON_FA_USERS "\xef\x83\x80"	// U+f0c0
#define ICON_FA_LINK "\xef\x83\x81"	// U+f0c1
#define ICON_FA_CLOUD "\xef\x83\x82"	// U+f0c2
#define ICON_FA_FLASK "\xef\x83\x83"	// U+f0c3
#define ICON_FA_SCISSORS "\xef\x83\x84"	// U+f0c4
#define ICON_FA_FILES_O "\xef\x83\x85"	// U+f0c5
#define ICON_FA_PAPERCLIP "\xef\x83\x86"	// U+f0c6
#define ICON_FA_FLOPPY_O "\xef\x83\x87"	// U+f0c7
#define ICON_FA_SQUARE "\xef\x83\x88"	// U+f0c8
#define ICON_FA_BARS "\xef\x83\x89"	// U+f0c9
#define ICON_FA_LIST_UL "\xef\x83\x8a"	// U+f0ca
#define ICON_FA_LIST_OL "\xef\x83\x8b"	// U+f0cb
#define ICON_FA_STRIKETHROUGH "\xef\x83\x8c"	// U+f0cc
#define ICON_FA_UNDERLINE "\xef\x83\x8d"	// U+f0cd
#define ICON_FA_TABLE "\xef\x83\x8e"	// U+f0ce
#define ICON_FA_MAGIC "\xef\x83\x90"	// U+f0d0
#define ICON_FA_TRUCK "\xef\x83\x91"	// U+f0d1
#define ICON_FA_PINTEREST "\xef\x83\x92"	// U+f0d2
#define ICON_FA_PINTEREST_SQUARE "\xef\x83\x93"	// U+f0d3
#define ICON_FA_GOOGLE_PLUS_SQUARE "\xef\x83\x94"	// U+f0d4
#define ICON_FA_GOOGLE_PLUS "\xef\x83\x95"	// U+f0d5
#define ICON_FA_MONEY "\xef\x83\x96"	// U+f0d6
#define ICON_FA_CARET_DOWN "\xef\x83\x97"	// U+f0d7
#define ICON_FA_CARET_UP "\xef\x83\x98"	// U+f0d8
#define ICON_FA_CARET_LEFT "\xef\x83\x99"	// U+f0d9
#define ICON_FA_CARET_RIGHT "\xef\x83\x9a"	// U+f0da
#define ICON_FA_COLUMNS "\xef\x83\x9b"	// U+f0db
#define ICON_FA_SORT "\xef\x83\x9c"	// U+f0dc
#define ICON_FA_SORT_DESC "\xef\x83\x9d"	// U+f0dd
#define ICON_FA_SORT_ASC "\xef\x83\x9e"	// U+f0de
#define ICON_FA_ENVELOPE "\xef\x83\xa0"	// U+f0e0
#define ICON_FA_LINKEDIN "\xef\x83\xa1"	// U+f0e1
#define ICON_FA_UNDO "\xef\x83\xa2"	// U+f0e2
#define ICON_FA_GAVEL "\xef\x83\xa3"	// U+f0e3
#define ICON_FA_TACHOMETER "\xef\x83\xa4"	// U+f0e4
#define ICON_FA_COMMENT_O "\xef\x83\xa5"	// U+f0e5
#define ICON_FA_COMMENTS_O "\xef\x83\xa6"	// U+f0e6
#define ICON_FA_BOLT "\xef\x83\xa7"	// U+f0e7
#define ICON_FA_SITEMAP "\xef\x83\xa8"	// U+f0e8
#define ICON_FA_UMBRELLA "\xef\x83\xa9"	// U+f0e9
#define ICON_FA_CLIPBOARD "\xef\x83\xaa"	// U+f0ea
#define ICON_FA_LIGHTBULB_O "\xef\x83\xab"	// U+f0eb
#define ICON_FA_EXCHANGE "\xef\x83\xac"	// U+f0ec
#define ICON_FA_CLOUD_DOWNLOAD "\xef\x83\xad"	// U+f0ed
#define ICON_FA_CLOUD_UPLOAD "\xef\x83\xae"	// U+f0ee
#define ICON_FA_USER_MD "\xef\x83\xb0"	// U+f0f0
#define ICON_FA_STETHOSCOPE "\xef\x83\xb1"	// U+f0f1
#define ICON_FA_SUITCASE "\xef\x83\xb2"	// U+f0f2
#define ICON_FA_BELL_O "\xef\x82\xa2"	// U+f0a2
#define ICON_FA_COFFEE "\xef\x83\xb4"	// U+f0f4
#define ICON_FA_CUTLERY "\xef\x83\xb5"	// U+f0f5
#define ICON_FA_FILE_TEXT_O "\xef\x83\xb6"	// U+f0f6
#define ICON_FA_BUILDING_O "\xef\x83\xb7"	// U+f0f7
#define ICON_FA_HOSPITAL_O "\xef\x83\xb8"	// U+f0f8
#define ICON_FA_AMBULANCE "\xef\x83\xb9"	// U+f0f9
#define ICON_FA_MEDKIT "\xef\x83\xba"	// U+f0fa
#define ICON_FA_FIGHTER_JET "\xef\x83\xbb"	// U+f0fb
#define ICON_FA_BEER "\xef\x83\xbc"	// U+f0fc
#define ICON_FA_H_SQUARE "\xef\x83\xbd"	// U+f0fd
#define ICON_FA_PLUS_SQUARE "\xef\x83\xbe"	// U+f0fe
#define ICON_FA_ANGLE_DOUBLE_LEFT "\xef\x84\x80"	// U+f100
#define ICON_FA_ANGLE_DOUBLE_RIGHT "\xef\x84\x81"	// U+f101
#define ICON_FA_ANGLE_DOUBLE_UP "\xef\x84\x82"	// U+f102
#define ICON_FA_ANGLE_DOUBLE_DOWN "\xef\x84\x83"	// U+f103
#define ICON_FA_ANGLE_LEFT "\xef\x84\x84"	// U+f104
#define ICON_FA_ANGLE_RIGHT "\xef\x84\x85"	// U+f105
#define ICON_FA_ANGLE_UP "\xef\x84\x86"	// U+f106
#define ICON_FA_ANGLE_DOWN "\xef\x84\x87"	// U+f107
#define ICON_FA_DESKTOP "\xef\x84\x88"	// U+f108
#define ICON_FA_LAPTOP "\xef\x84\x89"	// U+f109
#define ICON_FA_TABLET "\xef\x84\x8a"	// U+f10a
#define ICON_FA_MOBILE "\xef\x84\x8b"	// U+f10b
#define ICON_FA_CIRCLE_O "\xef\x84\x8c"	// U+f10c
#define ICON_FA_QUOTE_LEFT "\xef\x84\x8d"	// U+f10d
#define ICON_FA_QUOTE_RIGHT "\xef\x84\x8e"	// U+f10e
#define ICON_FA_SPINNER "\xef\x84\x90"	// U+f110
#define ICON_FA_CIRCLE "\xef\x84\x91"	// U+f111
#define ICON_FA_REPLY "\xef\x84\x92"	// U+f112
#define ICON_FA_GITHUB_ALT "\xef\x84\x93"	// U+f113
#define ICON_FA_FOLDER_O "\xef\x84\x94"	// U+f114
#define ICON_FA_FOLDER_OPEN_O "\xef\x84\x95"	// U+f115
#define ICON_FA_SMILE_O "\xef\x84\x98"	// U+f118
#define ICON_FA_FROWN_O "\xef\x84\x99"	// U+f119
#define ICON_FA_MEH_O "\xef\x84\x9a"	// U+f11a
#define ICON_FA_GAMEPAD "\xef\x84\x9b"	// U+f11b
#define ICON_FA_KEYBOARD_O "\xef\x84\x9c"	// U+f11c
#define ICON_FA_FLAG_O "\xef\x84\x9d"	// U+f11d
#define ICON_FA_FLAG_CHECKERED "\xef\x84\x9e"	// U+f11e
#define ICON_FA_TERMINAL "\xef\x84\xa0"	// U+f120
#define ICON_FA_CODE "\xef\x84\xa1"	// U+f121
#define ICON_FA_REPLY_ALL "\xef\x84\xa2"	// U+f122
#define ICON_FA_STAR_HALF_O "\xef\x84\xa3"	// U+f123
#define ICON_FA_LOCATION_ARROW "\xef\x84\xa4"	// U+f124
#define ICON_FA_CROP "\xef\x84\xa5"	// U+f125
#define ICON_FA_CODE_FORK "\xef\x84\xa6"	// U+f126
#define ICON_FA_CHAIN_BROKEN "\xef\x84\xa7"	// U+f127
#define ICON_FA_QUESTION "\xef\x84\xa8"	// U+f128
#define ICON_FA_INFO "\xef\x84\xa9"	// U+f129
#define ICON_FA_EXCLAMATION "\xef\x84\xaa"	// U+f12a
#define ICON_FA_SUPERSCRIPT "\xef\x84\xab"	// U+f12b
#define ICON_FA_SUBSCRIPT "\xef\x84\xac"	// U+f12c
#define ICON_FA_ERASER "\xef\x84\xad"	// U+f12d
#define ICON_FA_PUZZLE_PIECE "\xef\x84\xae"	// U+f12e
#define ICON_FA_MICROPHONE "\xef\x84\xb0"	// U+f130
#define ICON_FA_MICROPHONE_SLASH "\xef\x84\xb1"	// U+f131
#define ICON_FA_SHIELD "\xef\x84\xb2"	// U+f132
#define ICON_FA_CALENDAR_O "\xef\x84\xb3"	// U+f133
#define ICON_FA_FIRE_EXTINGUISHER "\xef\x84\xb4"	// U+f134
#define ICON_FA_ROCKET "\xef\x84\xb5"	// U+f135
#define ICON_FA_MAXCDN "\xef\x84\xb6"	// U+f136
#define ICON_FA_CHEVRON_CIRCLE_LEFT "\xef\x84\xb7"	// U+f137
#define ICON_FA_CHEVRON_CIRCLE_RIGHT "\xef\x84\xb8"	// U+f138
#define ICON_FA_CHEVRON_CIRCLE_UP "\xef\x84\xb9"	// U+f139
#define ICON_FA_CHEVRON_CIRCLE_DOWN "\xef\x84\xba"	// U+f13a
#define ICON_FA_HTML5 "\xef\x84\xbb"	// U+f13b
#define ICON_FA_CSS3 "\xef\x84\xbc"	// U+f13c
#define ICON_FA_ANCHOR "\xef\x84\xbd"	// U+f13d
#define ICON_FA_UNLOCK_ALT "\xef\x84\xbe"	// U+f13e
#define ICON_FA_BULLSEYE "\xef\x85\x80"	// U+f140
#define ICON_FA_ELLIPSIS_H "\xef\x85\x81"	// U+f141
#define ICON_FA_ELLIPSIS_V "\xef\x85\x82"	// U+f142
#define ICON_FA_RSS_SQUARE "\xef\x85\x83"	// U+f143
#define ICON_FA_PLAY_CIRCLE "\xef\x85\x84"	// U+f144
#define ICON_FA_TICKET "\xef\x85\x85"	// U+f145
#define ICON_FA_MINUS_SQUARE "\xef\x85\x86"	// U+f146
#define ICON_FA_MINUS_SQUARE_O "\xef\x85\x87"	// U+f147
#define ICON_FA_LEVEL_UP "\xef\x85\x88"	// U+f148
#define ICON_FA_LEVEL_DOWN "\xef\x85\x89"	// U+f149
#define ICON_FA_CHECK_SQUARE "\xef\x85\x8a"	// U+f14a
#define ICON_FA_PENCIL_SQUARE "\xef\x85\x8b"	// U+f14b
#define ICON_FA_EXTERNAL_LINK_SQUARE "\xef\x85\x8c"	// U+f14c
#define ICON_FA_SHARE_SQUARE "\xef\x85\x8d"	// U+f14d
#define ICON_FA_COMPASS "\xef\x85\x8e"	// U+f14e
#define ICON_FA_CARET_SQUARE_O_DOWN "\xef\x85\x90"	// U+f150
#define ICON_FA_CARET_SQUARE_O_UP "\xef\x85\x91"	// U+f151
#define ICON_FA_CARET_SQUARE_O_RIGHT "\xef\x85\x92"	// U+f152
#define ICON_FA_EUR "\xef\x85\x93"	// U+f153
#define ICON_FA_GBP "\xef\x85\x94"	// U+f154
#define ICON_FA_USD "\xef\x85\x95"	// U+f155
#define ICON_FA_INR "\xef\x85\x96"	// U+f156
#define ICON_FA_JPY "\xef\x85\x97"	// U+f157
#define ICON_FA_RUB "\xef\x85\x98"	// U+f158
#define ICON_FA_KRW "\xef\x85\x99"	// U+f159
#define ICON_FA_BTC "\xef\x85\x9a"	// U+f15a
#define ICON_FA_FILE "\xef\x85\x9b"	// U+f15b
#define ICON_FA_FILE_TEXT "\xef\x85\x9c"	// U+f15c
#define ICON_FA_SORT_ALPHA_ASC "\xef\x85\x9d"	// U+f15d
#define ICON_FA_SORT_ALPHA_DESC "\xef\x85\x9e"	// U+f15e
#define ICON_FA_SORT_AMOUNT_ASC "\xef\x85\xa0"	// U+f160
#define ICON_FA_SORT_AMOUNT_DESC "\xef\x85\xa1"	// U+f161
#define ICON_FA_SORT_NUMERIC_ASC "\xef\x85\xa2"	// U+f162
#define ICON_FA_SORT_NUMERIC_DESC "\xef\x85\xa3"	// U+f163
#define ICON_FA_THUMBS_UP "\xef\x85\xa4"	// U+f164
#define ICON_FA_THUMBS_DOWN "\xef\x85\xa5"	// U+f165
#define ICON_FA_YOUTUBE_SQUARE "\xef\x85\xa6"	// U+f166
#define ICON_FA_YOUTUBE "\xef\x85\xa7"	// U+f167
#define ICON_FA_XING "\xef\x85\xa8"	// U+f168
#define ICON_FA_XING_SQUARE "\xef\x85\xa9"	// U+f169
#define ICON_FA_YOUTUBE_PLAY "\xef\x85\xaa"	// U+f16a
#define ICON_FA_DROPBOX "\xef\x85\xab"	// U+f16b
#define ICON_FA_STACK_OVERFLOW "\xef\x85\xac"	// U+f16c
#define ICON_FA_INSTAGRAM "\xef\x85\xad"	// U+f16d
#define ICON_FA_FLICKR "\xef\x85\xae"	// U+f16e
#define ICON_FA_ADN "\xef\x85\xb0"	// U+f170
#define ICON_FA_BITBUCKET "\xef\x85\xb1"	// U+f171
#define ICON_FA_BITBUCKET_SQUARE "\xef\x85\xb2"	// U+f172
#define ICON_FA_TUMBLR "\xef\x85\xb3"	// U+f173
#define ICON_FA_TUMBLR_SQUARE "\xef\x85\xb4"	// U+f174
#define ICON_FA_LONG_ARROW_DOWN "\xef\x85\xb5"	// U+f175
#define ICON_FA_LONG_ARROW_UP "\xef\x85\xb6"	// U+f176
#define ICON_FA_LONG_ARROW_LEFT "\xef\x85\xb7"	// U+f177
#define ICON_FA_LONG_ARROW_RIGHT "\xef\x85\xb8"	// U+f178
#define ICON_FA_APPLE "\xef\x85\xb9"	// U+f179
#define ICON_FA_WINDOWS "\xef\x85\xba"	// U+f17a
#define ICON_FA_ANDROID "\xef\x85\xbb"	// U+f17b
#define ICON_FA_LINUX "\xef\x85\xbc"	// U+f17c
#define ICON_FA_DRIBBBLE "\xef\x85\xbd"	// U+f17d
#define ICON_FA_SKYPE "\xef\x85\xbe"	// U+f17e
#define ICON_FA_FOURSQUARE "\xef\x86\x80"	// U+f180
#define ICON_FA_TRELLO "\xef\x86\x81"	// U+f181
#define ICON_FA_FEMALE "\xef\x86\x82"	// U+f182
#define ICON_FA_MALE "\xef\x86\x83"	// U+f183
#define ICON_FA_GRATIPAY "\xef\x86\x84"	// U+f184
#define ICON_FA_SUN_O "\xef\x86\x85"	// U+f185
#define ICON_FA_MOON_O "\xef\x86\x86"	// U+f186
#define ICON_FA_ARCHIVE "\xef\x86\x87"	// U+f187
#define ICON_FA_BUG "\xef\x86\x88"	// U+f188
#define ICON_FA_VK "\xef\x86\x89"	// U+f189
#define ICON_FA_WEIBO "\xef\x86\x8a"	// U+f18a
#define ICON_FA_RENREN "\xef\x86\x8b"	// U+f18b
#define ICON_FA_PAGELINES "\xef\x86\x8c"	// U+f18c
#define ICON_FA_STACK_EXCHANGE "\xef\x86\x8d"	// U+f18d
#define ICON_FA_ARROW_CIRCLE_O_RIGHT "\xef\x86\x8e"	// U+f18e
#define ICON_FA_ARROW_CIRCLE_O_LEFT "\xef\x86\x90"	// U+f190
#define ICON_FA_CARET_SQUARE_O_LEFT "\xef\x86\x91"	// U+f191
#define ICON_FA_DOT_CIRCLE_O "\xef\x86\x92"	// U+f192
#define ICON_FA_WHEELCHAIR "\xef\x86\x93"	// U+f193
#define ICON_FA_VIMEO_SQUARE "\xef\x86\x94"	// U+f194
#define ICON_FA_TRY "\xef\x86\x95"	// U+f195
#define ICON_FA_PLUS_SQUARE_O "\xef\x86\x96"	// U+f196
#define ICON_FA_SPACE_SHUTTLE "\xef\x86\x97"	// U+f197
#define ICON_FA_SLACK "\xef\x86\x98"	// U+f198
#define ICON_FA_ENVELOPE_SQUARE "\xef\x86\x99"	// U+f199
#define ICON_FA_WORDPRESS "\xef\x86\x9a"	// U+f19a
#define ICON_FA_OPENID "\xef\x86\x9b"	// U+f19b
#define ICON_FA_UNIVERSITY "\xef\x86\x9c"	// U+f19c
#define ICON_FA_GRADUATION_CAP "\xef\x86\x9d"	// U+f19d
#define ICON_FA_YAHOO "\xef\x86\x9e"	// U+f19e
#define ICON_FA_GOOGLE "\xef\x86\xa0"	// U+f1a0
#define ICON_FA_REDDIT "\xef\x86\xa1"	// U+f1a1
#define ICON_FA_REDDIT_SQUARE "\xef\x86\xa2"	// U+f1a2
#define ICON_FA_STUMBLEUPON_CIRCLE "\xef\x86\xa3"	// U+f1a3
#define ICON_FA_STUMBLEUPON "\xef\x86\xa4"	// U+f1a4
#define ICON_FA_DELICIOUS "\xef\x86\xa5"	// U+f1a5
#define ICON_FA_DIGG "\xef\x86\xa6"	// U+f1a6
#define ICON_FA_PIED_PIPER_PP "\xef\x86\xa7"	// U+f1a7
#define ICON_FA_PIED_PIPER_ALT "\xef\x86\xa8"	// U+f1a8
#define ICON_FA_DRUPAL "\xef\x86\xa9"	// U+f1a9
#define ICON_FA_JOOMLA "\xef\x86\xaa"	// U+f1aa
#define ICON_FA_LANGUAGE "\xef\x86\xab"	// U+f1ab
#define ICON_FA_FAX "\xef\x86\xac"	// U+f1ac
#define ICON_FA_BUILDING "\xef\x86\xad"	// U+f1ad
#define ICON_FA_CHILD "\xef\x86\xae"	// U+f1ae
#define ICON_FA_PAW "\xef\x86\xb0"	// U+f1b0
#define ICON_FA_SPOON "\xef\x86\xb1"	// U+f1b1
#define ICON_FA_CUBE "\xef\x86\xb2"	// U+f1b2
#define ICON_FA_CUBES "\xef\x86\xb3"	// U+f1b3
#define ICON_FA_BEHANCE "\xef\x86\xb4"	// U+f1b4
#define ICON_FA_BEHANCE_SQUARE "\xef\x86\xb5"	// U+f1b5
#define ICON_FA_STEAM "\xef\x86\xb6"	// U+f1b6
#define ICON_FA_STEAM_SQUARE "\xef\x86\xb7"	// U+f1b7
#define ICON_FA_RECYCLE "\xef\x86\xb8"	// U+f1b8
#define ICON_FA_CAR "\xef\x86\xb9"	// U+f1b9
#define ICON_FA_TAXI "\xef\x86\xba"	// U+f1ba
#define ICON_FA_TREE "\xef\x86\xbb"	// U+f1bb
#define ICON_FA_SPOTIFY "\xef\x86\xbc"	// U+f1bc
#define ICON_FA_DEVIANTART "\xef\x86\xbd"	// U+f1bd
#define ICON_FA_SOUNDCLOUD "\xef\x86\xbe"	// U+f1be
#define ICON_FA_DATABASE "\xef\x87\x80"	// U+f1c0
#define ICON_FA_FILE_PDF_O "\xef\x87\x81"	// U+f1c1
#define ICON_FA_FILE_WORD_O "\xef\x87\x82"	// U+f1c2
#define ICON_FA_FILE_EXCEL_O "\xef\x87\x83"	// U+f1c3
#define ICON_FA_FILE_POWERPOINT_O "\xef\x87\x84"	// U+f1c4
#define ICON_FA_FILE_IMAGE_O "\xef\x87\x85"	// U+f1c5
#define ICON_FA_FILE_ARCHIVE_O "\xef\x87\x86"	// U+f1c6
#define ICON_FA_FILE_AUDIO_O "\xef\x87\x87"	// U+f1c7
#define ICON_FA_FILE_VIDEO_O "\xef\x87\x88"	// U+f1c8
#define ICON_FA_FILE_CODE_O "\xef\x87\x89"	// U+f1c9
#define ICON_FA_VINE "\xef\x87\x8a"	// U+f1ca
#define ICON_FA_CODEPEN "\xef\x87\x8b"	// U+f1cb
#define ICON_FA_JSFIDDLE "\xef\x87\x8c"	// U+f1cc
#define ICON_FA_LIFE_RING "\xef\x87\x8d"	// U+f1cd
#define ICON_FA_CIRCLE_O_NOTCH "\xef\x87\x8e"	// U+f1ce
#define ICON_FA_REBEL "\xef\x87\x90"	// U+f1d0
#define ICON_FA_EMPIRE "\xef\x87\x91"	// U+f1d1
#define ICON_FA_GIT_SQUARE "\xef\x87\x92"	// U+f1d2
#define ICON_FA_GIT "\xef\x87\x93"	// U+f1d3
#define ICON_FA_HACKER_NEWS "\xef\x87\x94"	// U+f1d4
#define ICON_FA_TENCENT_WEIBO "\xef\x87\x95"	// U+f1d5
#define ICON_FA_QQ "\xef\x87\x96"	// U+f1d6
#define ICON_FA_WEIXIN "\xef\x87\x97"	// U+f1d7
#define ICON_FA_PAPER_PLANE "\xef\x87\x98"	// U+f1d8
#define ICON_FA_PAPER_PLANE_O "\xef\x87\x99"	// U+f1d9
#define ICON_FA_HISTORY "\xef\x87\x9a"	// U+f1da
#define ICON_FA_CIRCLE_THIN "\xef\x87\x9b"	// U+f1db
#define ICON_FA_HEADER "\xef\x87\x9c"	// U+f1dc
#define ICON_FA_PARAGRAPH "\xef\x87\x9d"	// U+f1dd
#define ICON_FA_SLIDERS "\xef\x87\x9e"	// U+f1de
#define ICON_FA_SHARE_ALT "\xef\x87\xa0"	// U+f1e0
#define ICON_FA_SHARE_ALT_SQUARE "\xef\x87\xa1"	// U+f1e1
#define ICON_FA_BOMB "\xef\x87\xa2"	// U+f1e2
#define ICON_FA_FUTBOL_O "\xef\x87\xa3"	// U+f1e3
#define ICON_FA_TTY "\xef\x87\xa4"	// U+f1e4
#define ICON_FA_BINOCULARS "\xef\x87\xa5"	// U+f1e5
#define ICON_FA_PLUG "\xef\x87\xa6"	// U+f1e6
#define ICON_FA_SLIDESHARE "\xef\x87\xa7"	// U+f1e7
#define ICON_FA_TWITCH "\xef\x87\xa8"	// U+f1e8
#define ICON_FA_YELP "\xef\x87\xa9"	// U+f1e9
#define ICON_FA_NEWSPAPER_O "\xef\x87\xaa"	// U+f1ea
#define ICON_FA_WIFI "\xef\x87\xab"	// U+f1eb
#define ICON_FA_CALCULATOR "\xef\x87\xac"	// U+f1ec
#define ICON_FA_PAYPAL "\xef\x87\xad"	// U+f1ed
#define ICON_FA_GOOGLE_WALLET "\xef\x87\xae"	// U+f1ee
#define ICON_FA_CC_VISA "\xef\x87\xb0"	// U+f1f0
#define ICON_FA_CC_MASTERCARD "\xef\x87\xb1"	// U+f1f1
#define ICON_FA_CC_DISCOVER "\xef\x87\xb2"	// U+f1f2
#define ICON_FA_CC_AMEX "\xef\x87\xb3"	// U+f1f3
#define ICON_FA_CC_PAYPAL "\xef\x87\xb4"	// U+f1f4
#define ICON_FA_CC_STRIPE "\xef\x87\xb5"	// U+f1f5
#define ICON_FA_BELL_SLASH "\xef\x87\xb6"	// U+f1f6
#define ICON_FA_BELL_SLASH_O "\xef\x87\xb7"	// U+f1f7
#define ICON_FA_TRASH "\xef\x87\xb8"	// U+f1f8
#define ICON_FA_COPYRIGHT "\xef\x87\xb9"	// U+f1f9
#define ICON_FA_AT "\xef\x87\xba"	// U+f1fa
#define ICON_FA_EYEDROPPER "\xef\x87\xbb"	// U+f1fb
#define ICON_FA_PAINT_BRUSH "\xef\x87\xbc"	// U+f1fc
#define ICON_FA_BIRTHDAY_CAKE "\xef\x87\xbd"	// U+f1fd
#define ICON_FA_AREA_CHART "\xef\x87\xbe"	// U+f1fe
#define ICON_FA_PIE_CHART "\xef\x88\x80"	// U+f200
#define ICON_FA_LINE_CHART "\xef\x88\x81"	// U+f201
#define ICON_FA_LASTFM "\xef\x88\x82"	// U+f202
#define ICON_FA_LASTFM_SQUARE "\xef\x88\x83"	// U+f203
#define ICON_FA_TOGGLE_OFF "\xef\x88\x84"	// U+f204
#define ICON_FA_TOGGLE_ON "\xef\x88\x85"	// U+f205
#define ICON_FA_BICYCLE "\xef\x88\x86"	// U+f206
#define ICON_FA_BUS "\xef\x88\x87"	// U+f207
#define ICON_FA_IOXHOST "\xef\x88\x88"	// U+f208
#define ICON_FA_ANGELLIST "\xef\x88\x89"	// U+f209
#define ICON_FA_CC "\xef\x88\x8a"	// U+f20a
#define ICON_FA_ILS "\xef\x88\x8b"	// U+f20b
#define ICON_FA_MEANPATH "\xef\x88\x8c"	// U+f20c
#define ICON_FA_BUYSELLADS "\xef\x88\x8d"	// U+f20d
#define ICON_FA_CONNECTDEVELOP "\xef\x88\x8e"	// U+f20e
#define ICON_FA_DASHCUBE "\xef\x88\x90"	// U+f210
#define ICON_FA_FORUMBEE "\xef\x88\x91"	// U+f211
#define ICON_FA_LEANPUB "\xef\x88\x92"	// U+f212
#define ICON_FA_SELLSY "\xef\x88\x93"	// U+f213
#define ICON_FA_SHIRTSINBULK "\xef\x88\x94"	// U+f214
#define ICON_FA_SIMPLYBUILT "\xef\x88\x95"	// U+f215
#define ICON_FA_SKYATLAS "\xef\x88\x96"	// U+f216
#define ICON_FA_CART_PLUS "\xef\x88\x97"	// U+f217
#define ICON_FA_CART_ARROW_DOWN "\xef\x88\x98"	// U+f218
#define ICON_FA_DIAMOND "\xef\x88\x99"	// U+f219
#define ICON_FA_SHIP "\xef\x88\x9a"	// U+f21a
#define ICON_FA_USER_SECRET "\xef\x88\x9b"	// U+f21b
#define ICON_FA_MOTORCYCLE "\xef\x88\x9c"	// U+f21c
#define ICON_FA_STREET_VIEW "\xef\x88\x9d"	// U+f21d
#define ICON_FA_HEARTBEAT "\xef\x88\x9e"	// U+f21e
#define ICON_FA_VENUS "\xef\x88\xa1"	// U+f221
#define ICON_FA_MARS "\xef\x88\xa2"	// U+f222
#define ICON_FA_MERCURY "\xef\x88\xa3"	// U+f223
#define ICON_FA_TRANSGENDER "\xef\x88\xa4"	// U+f224
#define ICON_FA_TRANSGENDER_ALT "\xef\x88\xa5"	// U+f225
#define ICON_FA_VENUS_DOUBLE "\xef\x88\xa6"	// U+f226
#define ICON_FA_MARS_DOUBLE "\xef\x88\xa7"	// U+f227
#define ICON_FA_VENUS_MARS "\xef\x88\xa8"	// U+f228
#define ICON_FA_MARS_STROKE "\xef\x88\xa9"	// U+f229
#define ICON_FA_MARS_STROKE_V "\xef\x88\xaa"	// U+f22a
#define ICON_FA_MARS_STROKE_H "\xef\x88\xab"	// U+f22b
#define ICON_FA_NEUTER "\xef\x88\xac"	// U+f22c
#define ICON_FA_GENDERLESS "\xef\x88\xad"	// U+f22d
#define ICON_FA_FACEBOOK_OFFICIAL "\xef\x88\xb0"	// U+f230
#define ICON_FA_PINTEREST_P "\xef\x88\xb1"	// U+f231
#define ICON_FA_WHATSAPP "\xef\x88\xb2"	// U+f232
#define ICON_FA_SERVER "\xef\x88\xb3"	// U+f233
#define ICON_FA_USER_PLUS "\xef\x88\xb4"	// U+f234
#define ICON_FA_USER_TIMES "\xef\x88\xb5"	// U+f235
#define ICON_FA_BED "\xef\x88\xb6"	// U+f236
#define ICON_FA_VIACOIN "\xef\x88\xb7"	// U+f237
#define ICON_FA_TRAIN "\xef\x88\xb8"	// U+f238
#define ICON_FA_SUBWAY "\xef\x88\xb9"	// U+f239
#define ICON_FA_MEDIUM "\xef\x88\xba"	// U+f23a
#define ICON_FA_Y_COMBINATOR "\xef\x88\xbb"	// U+f23b
#define ICON_FA_OPTIN_MONSTER "\xef\x88\xbc"	// U+f23c
#define ICON_FA_OPENCART "\xef\x88\xbd"	// U+f23d
#define ICON_FA_EXPEDITEDSSL "\xef\x88\xbe"	// U+f23e
#define ICON_FA_BATTERY_FULL "\xef\x89\x80"	// U+f240
#define ICON_FA_BATTERY_THREE_QUARTERS "\xef\x89\x81"	// U+f241
#define ICON_FA_BATTERY_HALF "\xef\x89\x82"	// U+f242
#define ICON_FA_BATTERY_QUARTER "\xef\x89\x83"	// U+f243
#define ICON_FA_BATTERY_EMPTY "\xef\x89\x84"	// U+f244
#define ICON_FA_MOUSE_POINTER "\xef\x89\x85"	// U+f245
#define ICON_FA_I_CURSOR "\xef\x89\x86"	// U+f246
#define ICON_FA_OBJECT_GROUP "\xef\x89\x87"	// U+f247
#define ICON_FA_OBJECT_UNGROUP "\xef\x89\x88"	// U+f248
#define ICON_FA_STICKY_NOTE "\xef\x89\x89"	// U+f249
#define ICON_FA_STICKY_NOTE_O "\xef\x89\x8a"	// U+f24a
#define ICON_FA_CC_JCB "\xef\x89\x8b"	// U+f24b
#define ICON_FA_CC_DINERS_CLUB "\xef\x89\x8c"	// U+f24c
#define ICON_FA_CLONE "\xef\x89\x8d"	// U+f24d
#define ICON_FA_BALANCE_SCALE "\xef\x89\x8e"	// U+f24e
#define ICON_FA_HOURGLASS_O "\xef\x89\x90"	// U+f250
#define ICON_FA_HOURGLASS_START "\xef\x89\x91"	// U+f251
#define ICON_FA_HOURGLASS_HALF "\xef\x89\x92"	// U+f252
#define ICON_FA_HOURGLASS_END "\xef\x89\x93"	// U+f253
#define ICON_FA_HOURGLASS "\xef\x89\x94"	// U+f254
#define ICON_FA_HAND_ROCK_O "\xef\x89\x95"	// U+f255
#define ICON_FA_HAND_PAPER_O "\xef\x89\x96"	// U+f256
#define ICON_FA_HAND_SCISSORS_O "\xef\x89\x97"	// U+f257
#define ICON_FA_HAND_LIZARD_O "\xef\x89\x98"	// U+f258
#define ICON_FA_HAND_SPOCK_O "\xef\x89\x99"	// U+f259
#define ICON_FA_HAND_POINTER_O "\xef\x89\x9a"	// U+f25a
#define ICON_FA_HAND_PEACE_O "\xef\x89\x9b"	// U+f25b
#define ICON_FA_TRADEMARK "\xef\x89\x9c"	// U+f25c
#define ICON_FA_REGISTERED "\xef\x89\x9d"	// U+f25d
#define ICON_FA_CREATIVE_COMMONS "\xef\x89\x9e"	// U+f25e
#define ICON_FA_GG "\xef\x89\xa0"	// U+f260
#define ICON_FA_GG_CIRCLE "\xef\x89\xa1"	// U+f261
#define ICON_FA_TRIPADVISOR "\xef\x89\xa2"	// U+f262
#define ICON_FA_ODNOKLASSNIKI "\xef\x89\xa3"	// U+f263
#define ICON_FA_ODNOKLASSNIKI_SQUARE "\xef\x89\xa4"	// U+f264
#define ICON_FA_GET_POCKET "\xef\x89\xa5"	// U+f265
#define ICON_FA_WIKIPEDIA_W "\xef\x89\xa6"	// U+f266
#define ICON_FA_SAFARI "\xef\x89\xa7"	// U+f267
#define ICON_FA_CHROME "\xef\x89\xa8"	// U+f268
#define ICON_FA_FIREFOX "\xef\x89\xa9"	// U+f269
#define ICON_FA_OPERA "\xef\x89\xaa"	// U+f26a
#define ICON_FA_INTERNET_EXPLORER "\xef\x89\xab"	// U+f26b
#define ICON_FA_TELEVISION "\xef\x89\xac"	// U+f26c
#define ICON_FA_CONTAO "\xef\x89\xad"	// U+f26d
#define ICON_FA_500PX "\xef\x89\xae"	// U+f26e
#define ICON_FA_AMAZON "\xef\x89\xb0"	// U+f270
#define ICON_FA_CALENDAR_PLUS_O "\xef\x89\xb1"	// U+f271
#define ICON_FA_CALENDAR_MINUS_O "\xef\x89\xb2"	// U+f272
#define ICON_FA_CALENDAR_TIMES_O "\xef\x89\xb3"	// U+f273
#define ICON_FA_CALENDAR_CHECK_O "\xef\x89\xb4"	// U+f274
#define ICON_FA_INDUSTRY "\xef\x89\xb5"	// U+f275
#define ICON_FA_MAP_PIN "\xef\x89\xb6"	// U+f276
#define ICON_FA_MAP_SIGNS "\xef\x89\xb7"	// U+f277
#define ICON_FA_MAP_O "\xef\x89\xb8"	// U+f278
#define ICON_FA_MAP "\xef\x89\xb9"	// U+f279
#define ICON_FA_COMMENTING "\xef\x89\xba"	// U+f27a
#define ICON_FA_COMMENTING_O "\xef\x89\xbb"	// U+f27b
#define ICON_FA_HOUZZ "\xef\x89\xbc"	// U+f27c
#define ICON_FA_VIMEO "\xef\x89\xbd"	// U+f27d
#define ICON_FA_BLACK_TIE "\xef\x89\xbe"	// U+f27e
#define ICON_FA_FONTICONS "\xef\x8a\x80"	// U+f280
#define ICON_FA_REDDIT_ALIEN "\xef\x8a\x81"	// U+f281
#define ICON_FA_EDGE "\xef\x8a\x82"	// U+f282
#define ICON_FA_CREDIT_CARD_ALT "\xef\x8a\x83"	// U+f283
#define ICON_FA_CODIEPIE "\xef\x8a\x84"	// U+f284
#define ICON_FA_MODX "\xef\x8a\x85"	// U+f285
#define ICON_FA_FORT_AWESOME "\xef\x8a\x86"	// U+f286
#define ICON_FA_USB "\xef\x8a\x87"	// U+f287
#define ICON_FA_PRODUCT_HUNT "\xef\x8a\x88"	// U+f288
#define ICON_FA_MIXCLOUD "\xef\x8a\x89"	// U+f289
#define ICON_FA_SCRIBD "\xef\x8a\x8a"	// U+f28a
#define ICON_FA_PAUSE_CIRCLE "\xef\x8a\x8b"	// U+f28b
#define ICON_FA_PAUSE_CIRCLE_O "\xef\x8a\x8c"	// U+f28c
#define ICON_FA_STOP_CIRCLE "\xef\x8a\x8d"	// U+f28d
#define ICON_FA_STOP_CIRCLE_O "\xef\x8a\x8e"	// U+f28e
#define ICON_FA_SHOPPING_BAG "\xef\x8a\x90"	// U+f290
#define ICON_FA_SHOPPING_BASKET "\xef\x8a\x91"	// U+f291
#define ICON_FA_HASHTAG "\xef\x8a\x92"	// U+f292
#define ICON_FA_BLUETOOTH "\xef\x8a\x93"	// U+f293
#define ICON_FA_BLUETOOTH_B "\xef\x8a\x94"	// U+f294
#define ICON_FA_PERCENT "\xef\x8a\x95"	// U+f295
#define ICON_FA_GITLAB "\xef\x8a\x96"	// U+f296
#define ICON_FA_WPBEGINNER "\xef\x8a\x97"	// U+f297
#define ICON_FA_WPFORMS "\xef\x8a\x98"	// U+f298
#define ICON_FA_ENVIRA "\xef\x8a\x99"	// U+f299
#define ICON_FA_UNIVERSAL_ACCESS "\xef\x8a\x9a"	// U+f29a
#define ICON_FA_WHEELCHAIR_ALT "\xef\x8a\x9b"	// U+f29b
#define ICON_FA_QUESTION_CIRCLE_O "\xef\x8a\x9c"	// U+f29c
#define ICON_FA_BLIND "\xef\x8a\x9d"	// U+f29d
#define ICON_FA_AUDIO_DESCRIPTION "\xef\x8a\x9e"	// U+f29e
#define ICON_FA_VOLUME_CONTROL_PHONE "\xef\x8a\xa0"	// U+f2a0
#define ICON_FA_BRAILLE "\xef\x8a\xa1"	// U+f2a1
#define ICON_FA_ASSISTIVE_LISTENING_SYSTEMS "\xef\x8a\xa2"	// U+f2a2
#define ICON_FA_AMERICAN_SIGN_LANGUAGE_INTERPRETING "\xef\x8a\xa3"	// U+f2a3
#define ICON_FA_DEAF "\xef\x8a\xa4"	// U+f2a4
#define ICON_FA_GLIDE "\xef\x8a\xa5"	// U+f2a5
#define ICON_FA_GLIDE_G "\xef\x8a\xa6"	// U+f2a6
#define ICON_FA_SIGN_LANGUAGE "\xef\x8a\xa7"	// U+f2a7
#define ICON_FA_LOW_VISION "\xef\x8a\xa8"	// U+f2a8
#define ICON_FA_VIADEO "\xef\x8a\xa9"	// U+f2a9
#define ICON_FA_VIADEO_SQUARE "\xef\x8a\xaa"	// U+f2aa
#define ICON_FA_SNAPCHAT "\xef\x8a\xab"	// U+f2ab
#define ICON_FA_SNAPCHAT_GHOST "\xef\x8a\xac"	// U+f2ac
#define ICON_FA_SNAPCHAT_SQUARE "\xef\x8a\xad"	// U+f2ad
#define ICON_FA_PIED_PIPER "\xef\x8a\xae"	// U+f2ae
#define ICON_FA_FIRST_ORDER "\xef\x8a\xb0"	// U+f2b0
#define ICON_FA_YOAST "\xef\x8a\xb1"	// U+f2b1
#define ICON_FA_THEMEISLE "\xef\x8a\xb2"	// U+f2b2
#define ICON_FA_GOOGLE_PLUS_OFFICIAL "\xef\x8a\xb3"	// U+f2b3
#define ICON_FA_FONT_AWESOME "\xef\x8a\xb4"	// U+f2b4
#define ICON_FA_HANDSHAKE_O "\xef\x8a\xb5"	// U+f2b5
#define ICON_FA_ENVELOPE_OPEN "\xef\x8a\xb6"	// U+f2b6
#define ICON_FA_ENVELOPE_OPEN_O "\xef\x8a\xb7"	// U+f2b7
#define ICON_FA_LINODE "\xef\x8a\xb8"	// U+f2b8
#define ICON_FA_ADDRESS_BOOK "\xef\x8a\xb9"	// U+f2b9
#define ICON_FA_ADDRESS_BOOK_O "\xef\x8a\xba"	// U+f2ba
#define ICON_FA_ADDRESS_CARD "\xef\x8a\xbb"	// U+f2bb
#define ICON_FA_ADDRESS_CARD_O "\xef\x8a\xbc"	// U+f2bc
#define ICON_FA_USER_CIRCLE "\xef\x8a\xbd"	// U+f2bd
#define ICON_FA_USER_CIRCLE_O "\xef\x8a\xbe"	// U+f2be
#define ICON_FA_USER_O "\xef\x8b\x80"	// U+f2c0
#define ICON_FA_ID_BADGE "\xef\x8b\x81"	// U+f2c1
#define ICON_FA_ID_CARD "\xef\x8b\x82"	// U+f2c2
#define ICON_FA_ID_CARD_O "\xef\x8b\x83"	// U+f2c3
#define ICON_FA_QUORA "\xef\x8b\x84"	// U+f2c4
#define ICON_FA_FREE_CODE_CAMP "\xef\x8b\x85"	// U+f2c5
#define ICON_FA_TELEGRAM "\xef\x8b\x86"	// U+f2c6
#define ICON_FA_THERMOMETER_FULL "\xef\x8b\x87"	// U+f2c7
#define ICON_FA_THERMOMETER_THREE_QUARTERS "\xef\x8b\x88"	// U+f2c8
#define ICON_FA_THERMOMETER_HALF "\xef\x8b\x89"	// U+f2c9
#define ICON_FA_THERMOMETER_QUARTER "\xef\x8b\x8a"	// U+f2ca
#define ICON_FA_THERMOMETER_EMPTY "\xef\x8b\x8b"	// U+f2cb
#define ICON_FA_SHOWER "\xef\x8b\x8c"	// U+f2cc
#define ICON_FA_BATH "\xef\x8b\x8d"	// U+f2cd
#define ICON_FA_PODCAST "\xef\x8b\x8e"	// U+f2ce
#define ICON_FA_WINDOW_MAXIMIZE "\xef\x8b\x90"	// U+f2d0
#define ICON_FA_WINDOW_MINIMIZE "\xef\x8b\x91"	// U+f2d1
#define ICON_FA_WINDOW_RESTORE "\xef\x8b\x92"	// U+f2d2
#define ICON_FA_WINDOW_CLOSE "\xef\x8b\x93"	// U+f2d3
#define ICON_FA_WINDOW_CLOSE_O "\xef\x8b\x94"	// U+f2d4
#define ICON_FA_BANDCAMP "\xef\x8b\x95"	// U+f2d5
#define ICON_FA_GRAV "\xef\x8b\x96"	// U+f2d6
#define ICON_FA_ETSY "\xef\x8b\x97"	// U+f2d7
#define ICON_FA_IMDB "\xef\x8b\x98"	// U+f2d8
#define ICON_FA_RAVELRY "\xef\x8b\x99"	// U+f2d9
#define ICON_FA_EERCAST "\xef\x8b\x9a"	// U+f2da
#define ICON_FA_MICROCHIP "\xef\x8b\x9b"	// U+f2db
#define ICON_FA_SNOWFLAKE_O "\xef\x8b\x9c"	// U+f2dc
#define ICON_FA_SUPERPOWERS "\xef\x8b\x9d"	// U+f2dd
#define ICON_FA_WPEXPLORER "\xef\x8b\x9e"	// U+f2de
#define ICON_FA_MEETUP "\xef\x8b\xa0"	// U+f2e0

#pragma endregion

#pragma region Codicons

// https://github.com/juliettef/IconFontCppHeaders/blob/main/IconsCodicons.h

#define ICON_CI_ADD "\xee\xa9\xa0"	// U+ea60
#define ICON_CI_PLUS "\xee\xa9\xa0"	// U+ea60
#define ICON_CI_GIST_NEW "\xee\xa9\xa0"	// U+ea60
#define ICON_CI_REPO_CREATE "\xee\xa9\xa0"	// U+ea60
#define ICON_CI_LIGHTBULB "\xee\xa9\xa1"	// U+ea61
#define ICON_CI_LIGHT_BULB "\xee\xa9\xa1"	// U+ea61
#define ICON_CI_REPO "\xee\xa9\xa2"	// U+ea62
#define ICON_CI_REPO_DELETE "\xee\xa9\xa2"	// U+ea62
#define ICON_CI_GIST_FORK "\xee\xa9\xa3"	// U+ea63
#define ICON_CI_REPO_FORKED "\xee\xa9\xa3"	// U+ea63
#define ICON_CI_GIT_PULL_REQUEST "\xee\xa9\xa4"	// U+ea64
#define ICON_CI_GIT_PULL_REQUEST_ABANDONED "\xee\xa9\xa4"	// U+ea64
#define ICON_CI_RECORD_KEYS "\xee\xa9\xa5"	// U+ea65
#define ICON_CI_KEYBOARD "\xee\xa9\xa5"	// U+ea65
#define ICON_CI_TAG "\xee\xa9\xa6"	// U+ea66
#define ICON_CI_GIT_PULL_REQUEST_LABEL "\xee\xa9\xa6"	// U+ea66
#define ICON_CI_TAG_ADD "\xee\xa9\xa6"	// U+ea66
#define ICON_CI_TAG_REMOVE "\xee\xa9\xa6"	// U+ea66
#define ICON_CI_PERSON "\xee\xa9\xa7"	// U+ea67
#define ICON_CI_PERSON_FOLLOW "\xee\xa9\xa7"	// U+ea67
#define ICON_CI_PERSON_OUTLINE "\xee\xa9\xa7"	// U+ea67
#define ICON_CI_PERSON_FILLED "\xee\xa9\xa7"	// U+ea67
#define ICON_CI_SOURCE_CONTROL "\xee\xa9\xa8"	// U+ea68
#define ICON_CI_MIRROR "\xee\xa9\xa9"	// U+ea69
#define ICON_CI_MIRROR_PUBLIC "\xee\xa9\xa9"	// U+ea69
#define ICON_CI_STAR "\xee\xa9\xaa"	// U+ea6a
#define ICON_CI_STAR_ADD "\xee\xa9\xaa"	// U+ea6a
#define ICON_CI_STAR_DELETE "\xee\xa9\xaa"	// U+ea6a
#define ICON_CI_STAR_EMPTY "\xee\xa9\xaa"	// U+ea6a
#define ICON_CI_COMMENT "\xee\xa9\xab"	// U+ea6b
#define ICON_CI_COMMENT_ADD "\xee\xa9\xab"	// U+ea6b
#define ICON_CI_ALERT "\xee\xa9\xac"	// U+ea6c
#define ICON_CI_WARNING "\xee\xa9\xac"	// U+ea6c
#define ICON_CI_SEARCH "\xee\xa9\xad"	// U+ea6d
#define ICON_CI_SEARCH_SAVE "\xee\xa9\xad"	// U+ea6d
#define ICON_CI_LOG_OUT "\xee\xa9\xae"	// U+ea6e
#define ICON_CI_SIGN_OUT "\xee\xa9\xae"	// U+ea6e
#define ICON_CI_LOG_IN "\xee\xa9\xaf"	// U+ea6f
#define ICON_CI_SIGN_IN "\xee\xa9\xaf"	// U+ea6f
#define ICON_CI_EYE "\xee\xa9\xb0"	// U+ea70
#define ICON_CI_EYE_UNWATCH "\xee\xa9\xb0"	// U+ea70
#define ICON_CI_EYE_WATCH "\xee\xa9\xb0"	// U+ea70
#define ICON_CI_CIRCLE_FILLED "\xee\xa9\xb1"	// U+ea71
#define ICON_CI_PRIMITIVE_DOT "\xee\xa9\xb1"	// U+ea71
#define ICON_CI_CLOSE_DIRTY "\xee\xa9\xb1"	// U+ea71
#define ICON_CI_DEBUG_BREAKPOINT "\xee\xa9\xb1"	// U+ea71
#define ICON_CI_DEBUG_BREAKPOINT_DISABLED "\xee\xa9\xb1"	// U+ea71
#define ICON_CI_DEBUG_HINT "\xee\xa9\xb1"	// U+ea71
#define ICON_CI_TERMINAL_DECORATION_SUCCESS "\xee\xa9\xb1"	// U+ea71
#define ICON_CI_PRIMITIVE_SQUARE "\xee\xa9\xb2"	// U+ea72
#define ICON_CI_EDIT "\xee\xa9\xb3"	// U+ea73
#define ICON_CI_PENCIL "\xee\xa9\xb3"	// U+ea73
#define ICON_CI_INFO "\xee\xa9\xb4"	// U+ea74
#define ICON_CI_ISSUE_OPENED "\xee\xa9\xb4"	// U+ea74
#define ICON_CI_GIST_PRIVATE "\xee\xa9\xb5"	// U+ea75
#define ICON_CI_GIT_FORK_PRIVATE "\xee\xa9\xb5"	// U+ea75
#define ICON_CI_LOCK "\xee\xa9\xb5"	// U+ea75
#define ICON_CI_MIRROR_PRIVATE "\xee\xa9\xb5"	// U+ea75
#define ICON_CI_CLOSE "\xee\xa9\xb6"	// U+ea76
#define ICON_CI_REMOVE_CLOSE "\xee\xa9\xb6"	// U+ea76
#define ICON_CI_X "\xee\xa9\xb6"	// U+ea76
#define ICON_CI_REPO_SYNC "\xee\xa9\xb7"	// U+ea77
#define ICON_CI_SYNC "\xee\xa9\xb7"	// U+ea77
#define ICON_CI_CLONE "\xee\xa9\xb8"	// U+ea78
#define ICON_CI_DESKTOP_DOWNLOAD "\xee\xa9\xb8"	// U+ea78
#define ICON_CI_BEAKER "\xee\xa9\xb9"	// U+ea79
#define ICON_CI_MICROSCOPE "\xee\xa9\xb9"	// U+ea79
#define ICON_CI_VM "\xee\xa9\xba"	// U+ea7a
#define ICON_CI_DEVICE_DESKTOP "\xee\xa9\xba"	// U+ea7a
#define ICON_CI_FILE "\xee\xa9\xbb"	// U+ea7b
#define ICON_CI_MORE "\xee\xa9\xbc"	// U+ea7c
#define ICON_CI_ELLIPSIS "\xee\xa9\xbc"	// U+ea7c
#define ICON_CI_KEBAB_HORIZONTAL "\xee\xa9\xbc"	// U+ea7c
#define ICON_CI_MAIL_REPLY "\xee\xa9\xbd"	// U+ea7d
#define ICON_CI_REPLY "\xee\xa9\xbd"	// U+ea7d
#define ICON_CI_ORGANIZATION "\xee\xa9\xbe"	// U+ea7e
#define ICON_CI_ORGANIZATION_FILLED "\xee\xa9\xbe"	// U+ea7e
#define ICON_CI_ORGANIZATION_OUTLINE "\xee\xa9\xbe"	// U+ea7e
#define ICON_CI_NEW_FILE "\xee\xa9\xbf"	// U+ea7f
#define ICON_CI_FILE_ADD "\xee\xa9\xbf"	// U+ea7f
#define ICON_CI_NEW_FOLDER "\xee\xaa\x80"	// U+ea80
#define ICON_CI_FILE_DIRECTORY_CREATE "\xee\xaa\x80"	// U+ea80
#define ICON_CI_TRASH "\xee\xaa\x81"	// U+ea81
#define ICON_CI_TRASHCAN "\xee\xaa\x81"	// U+ea81
#define ICON_CI_HISTORY "\xee\xaa\x82"	// U+ea82
#define ICON_CI_CLOCK "\xee\xaa\x82"	// U+ea82
#define ICON_CI_FOLDER "\xee\xaa\x83"	// U+ea83
#define ICON_CI_FILE_DIRECTORY "\xee\xaa\x83"	// U+ea83
#define ICON_CI_SYMBOL_FOLDER "\xee\xaa\x83"	// U+ea83
#define ICON_CI_LOGO_GITHUB "\xee\xaa\x84"	// U+ea84
#define ICON_CI_MARK_GITHUB "\xee\xaa\x84"	// U+ea84
#define ICON_CI_GITHUB "\xee\xaa\x84"	// U+ea84
#define ICON_CI_TERMINAL "\xee\xaa\x85"	// U+ea85
#define ICON_CI_CONSOLE "\xee\xaa\x85"	// U+ea85
#define ICON_CI_REPL "\xee\xaa\x85"	// U+ea85
#define ICON_CI_ZAP "\xee\xaa\x86"	// U+ea86
#define ICON_CI_SYMBOL_EVENT "\xee\xaa\x86"	// U+ea86
#define ICON_CI_ERROR "\xee\xaa\x87"	// U+ea87
#define ICON_CI_STOP "\xee\xaa\x87"	// U+ea87
#define ICON_CI_VARIABLE "\xee\xaa\x88"	// U+ea88
#define ICON_CI_SYMBOL_VARIABLE "\xee\xaa\x88"	// U+ea88
#define ICON_CI_ARRAY "\xee\xaa\x8a"	// U+ea8a
#define ICON_CI_SYMBOL_ARRAY "\xee\xaa\x8a"	// U+ea8a
#define ICON_CI_SYMBOL_MODULE "\xee\xaa\x8b"	// U+ea8b
#define ICON_CI_SYMBOL_PACKAGE "\xee\xaa\x8b"	// U+ea8b
#define ICON_CI_SYMBOL_NAMESPACE "\xee\xaa\x8b"	// U+ea8b
#define ICON_CI_SYMBOL_OBJECT "\xee\xaa\x8b"	// U+ea8b
#define ICON_CI_SYMBOL_METHOD "\xee\xaa\x8c"	// U+ea8c
#define ICON_CI_SYMBOL_FUNCTION "\xee\xaa\x8c"	// U+ea8c
#define ICON_CI_SYMBOL_CONSTRUCTOR "\xee\xaa\x8c"	// U+ea8c
#define ICON_CI_SYMBOL_BOOLEAN "\xee\xaa\x8f"	// U+ea8f
#define ICON_CI_SYMBOL_NULL "\xee\xaa\x8f"	// U+ea8f
#define ICON_CI_SYMBOL_NUMERIC "\xee\xaa\x90"	// U+ea90
#define ICON_CI_SYMBOL_NUMBER "\xee\xaa\x90"	// U+ea90
#define ICON_CI_SYMBOL_STRUCTURE "\xee\xaa\x91"	// U+ea91
#define ICON_CI_SYMBOL_STRUCT "\xee\xaa\x91"	// U+ea91
#define ICON_CI_SYMBOL_PARAMETER "\xee\xaa\x92"	// U+ea92
#define ICON_CI_SYMBOL_TYPE_PARAMETER "\xee\xaa\x92"	// U+ea92
#define ICON_CI_SYMBOL_KEY "\xee\xaa\x93"	// U+ea93
#define ICON_CI_SYMBOL_TEXT "\xee\xaa\x93"	// U+ea93
#define ICON_CI_SYMBOL_REFERENCE "\xee\xaa\x94"	// U+ea94
#define ICON_CI_GO_TO_FILE "\xee\xaa\x94"	// U+ea94
#define ICON_CI_SYMBOL_ENUM "\xee\xaa\x95"	// U+ea95
#define ICON_CI_SYMBOL_VALUE "\xee\xaa\x95"	// U+ea95
#define ICON_CI_SYMBOL_RULER "\xee\xaa\x96"	// U+ea96
#define ICON_CI_SYMBOL_UNIT "\xee\xaa\x96"	// U+ea96
#define ICON_CI_ACTIVATE_BREAKPOINTS "\xee\xaa\x97"	// U+ea97
#define ICON_CI_ARCHIVE "\xee\xaa\x98"	// U+ea98
#define ICON_CI_ARROW_BOTH "\xee\xaa\x99"	// U+ea99
#define ICON_CI_ARROW_DOWN "\xee\xaa\x9a"	// U+ea9a
#define ICON_CI_ARROW_LEFT "\xee\xaa\x9b"	// U+ea9b
#define ICON_CI_ARROW_RIGHT "\xee\xaa\x9c"	// U+ea9c
#define ICON_CI_ARROW_SMALL_DOWN "\xee\xaa\x9d"	// U+ea9d
#define ICON_CI_ARROW_SMALL_LEFT "\xee\xaa\x9e"	// U+ea9e
#define ICON_CI_ARROW_SMALL_RIGHT "\xee\xaa\x9f"	// U+ea9f
#define ICON_CI_ARROW_SMALL_UP "\xee\xaa\xa0"	// U+eaa0
#define ICON_CI_ARROW_UP "\xee\xaa\xa1"	// U+eaa1
#define ICON_CI_BELL "\xee\xaa\xa2"	// U+eaa2
#define ICON_CI_BOLD "\xee\xaa\xa3"	// U+eaa3
#define ICON_CI_BOOK "\xee\xaa\xa4"	// U+eaa4
#define ICON_CI_BOOKMARK "\xee\xaa\xa5"	// U+eaa5
#define ICON_CI_DEBUG_BREAKPOINT_CONDITIONAL_UNVERIFIED "\xee\xaa\xa6"	// U+eaa6
#define ICON_CI_DEBUG_BREAKPOINT_CONDITIONAL "\xee\xaa\xa7"	// U+eaa7
#define ICON_CI_DEBUG_BREAKPOINT_CONDITIONAL_DISABLED "\xee\xaa\xa7"	// U+eaa7
#define ICON_CI_DEBUG_BREAKPOINT_DATA_UNVERIFIED "\xee\xaa\xa8"	// U+eaa8
#define ICON_CI_DEBUG_BREAKPOINT_DATA "\xee\xaa\xa9"	// U+eaa9
#define ICON_CI_DEBUG_BREAKPOINT_DATA_DISABLED "\xee\xaa\xa9"	// U+eaa9
#define ICON_CI_DEBUG_BREAKPOINT_LOG_UNVERIFIED "\xee\xaa\xaa"	// U+eaaa
#define ICON_CI_DEBUG_BREAKPOINT_LOG "\xee\xaa\xab"	// U+eaab
#define ICON_CI_DEBUG_BREAKPOINT_LOG_DISABLED "\xee\xaa\xab"	// U+eaab
#define ICON_CI_BRIEFCASE "\xee\xaa\xac"	// U+eaac
#define ICON_CI_BROADCAST "\xee\xaa\xad"	// U+eaad
#define ICON_CI_BROWSER "\xee\xaa\xae"	// U+eaae
#define ICON_CI_BUG "\xee\xaa\xaf"	// U+eaaf
#define ICON_CI_CALENDAR "\xee\xaa\xb0"	// U+eab0
#define ICON_CI_CASE_SENSITIVE "\xee\xaa\xb1"	// U+eab1
#define ICON_CI_CHECK "\xee\xaa\xb2"	// U+eab2
#define ICON_CI_CHECKLIST "\xee\xaa\xb3"	// U+eab3
#define ICON_CI_CHEVRON_DOWN "\xee\xaa\xb4"	// U+eab4
#define ICON_CI_CHEVRON_LEFT "\xee\xaa\xb5"	// U+eab5
#define ICON_CI_CHEVRON_RIGHT "\xee\xaa\xb6"	// U+eab6
#define ICON_CI_CHEVRON_UP "\xee\xaa\xb7"	// U+eab7
#define ICON_CI_CHROME_CLOSE "\xee\xaa\xb8"	// U+eab8
#define ICON_CI_CHROME_MAXIMIZE "\xee\xaa\xb9"	// U+eab9
#define ICON_CI_CHROME_MINIMIZE "\xee\xaa\xba"	// U+eaba
#define ICON_CI_CHROME_RESTORE "\xee\xaa\xbb"	// U+eabb
#define ICON_CI_CIRCLE_OUTLINE "\xee\xaa\xbc"	// U+eabc
#define ICON_CI_CIRCLE "\xee\xaa\xbc"	// U+eabc
#define ICON_CI_DEBUG_BREAKPOINT_UNVERIFIED "\xee\xaa\xbc"	// U+eabc
#define ICON_CI_TERMINAL_DECORATION_INCOMPLETE "\xee\xaa\xbc"	// U+eabc
#define ICON_CI_CIRCLE_SLASH "\xee\xaa\xbd"	// U+eabd
#define ICON_CI_CIRCUIT_BOARD "\xee\xaa\xbe"	// U+eabe
#define ICON_CI_CLEAR_ALL "\xee\xaa\xbf"	// U+eabf
#define ICON_CI_CLIPPY "\xee\xab\x80"	// U+eac0
#define ICON_CI_CLOSE_ALL "\xee\xab\x81"	// U+eac1
#define ICON_CI_CLOUD_DOWNLOAD "\xee\xab\x82"	// U+eac2
#define ICON_CI_CLOUD_UPLOAD "\xee\xab\x83"	// U+eac3
#define ICON_CI_CODE "\xee\xab\x84"	// U+eac4
#define ICON_CI_COLLAPSE_ALL "\xee\xab\x85"	// U+eac5
#define ICON_CI_COLOR_MODE "\xee\xab\x86"	// U+eac6
#define ICON_CI_COMMENT_DISCUSSION "\xee\xab\x87"	// U+eac7
#define ICON_CI_CREDIT_CARD "\xee\xab\x89"	// U+eac9
#define ICON_CI_DASH "\xee\xab\x8c"	// U+eacc
#define ICON_CI_DASHBOARD "\xee\xab\x8d"	// U+eacd
#define ICON_CI_DATABASE "\xee\xab\x8e"	// U+eace
#define ICON_CI_DEBUG_CONTINUE "\xee\xab\x8f"	// U+eacf
#define ICON_CI_DEBUG_DISCONNECT "\xee\xab\x90"	// U+ead0
#define ICON_CI_DEBUG_PAUSE "\xee\xab\x91"	// U+ead1
#define ICON_CI_DEBUG_RESTART "\xee\xab\x92"	// U+ead2
#define ICON_CI_DEBUG_START "\xee\xab\x93"	// U+ead3
#define ICON_CI_DEBUG_STEP_INTO "\xee\xab\x94"	// U+ead4
#define ICON_CI_DEBUG_STEP_OUT "\xee\xab\x95"	// U+ead5
#define ICON_CI_DEBUG_STEP_OVER "\xee\xab\x96"	// U+ead6
#define ICON_CI_DEBUG_STOP "\xee\xab\x97"	// U+ead7
#define ICON_CI_DEBUG "\xee\xab\x98"	// U+ead8
#define ICON_CI_DEVICE_CAMERA_VIDEO "\xee\xab\x99"	// U+ead9
#define ICON_CI_DEVICE_CAMERA "\xee\xab\x9a"	// U+eada
#define ICON_CI_DEVICE_MOBILE "\xee\xab\x9b"	// U+eadb
#define ICON_CI_DIFF_ADDED "\xee\xab\x9c"	// U+eadc
#define ICON_CI_DIFF_IGNORED "\xee\xab\x9d"	// U+eadd
#define ICON_CI_DIFF_MODIFIED "\xee\xab\x9e"	// U+eade
#define ICON_CI_DIFF_REMOVED "\xee\xab\x9f"	// U+eadf
#define ICON_CI_DIFF_RENAMED "\xee\xab\xa0"	// U+eae0
#define ICON_CI_DIFF "\xee\xab\xa1"	// U+eae1
#define ICON_CI_DIFF_SIDEBYSIDE "\xee\xab\xa1"	// U+eae1
#define ICON_CI_DISCARD "\xee\xab\xa2"	// U+eae2
#define ICON_CI_EDITOR_LAYOUT "\xee\xab\xa3"	// U+eae3
#define ICON_CI_EMPTY_WINDOW "\xee\xab\xa4"	// U+eae4
#define ICON_CI_EXCLUDE "\xee\xab\xa5"	// U+eae5
#define ICON_CI_EXTENSIONS "\xee\xab\xa6"	// U+eae6
#define ICON_CI_EYE_CLOSED "\xee\xab\xa7"	// U+eae7
#define ICON_CI_FILE_BINARY "\xee\xab\xa8"	// U+eae8
#define ICON_CI_FILE_CODE "\xee\xab\xa9"	// U+eae9
#define ICON_CI_FILE_MEDIA "\xee\xab\xaa"	// U+eaea
#define ICON_CI_FILE_PDF "\xee\xab\xab"	// U+eaeb
#define ICON_CI_FILE_SUBMODULE "\xee\xab\xac"	// U+eaec
#define ICON_CI_FILE_SYMLINK_DIRECTORY "\xee\xab\xad"	// U+eaed
#define ICON_CI_FILE_SYMLINK_FILE "\xee\xab\xae"	// U+eaee
#define ICON_CI_FILE_ZIP "\xee\xab\xaf"	// U+eaef
#define ICON_CI_FILES "\xee\xab\xb0"	// U+eaf0
#define ICON_CI_FILTER "\xee\xab\xb1"	// U+eaf1
#define ICON_CI_FLAME "\xee\xab\xb2"	// U+eaf2
#define ICON_CI_FOLD_DOWN "\xee\xab\xb3"	// U+eaf3
#define ICON_CI_FOLD_UP "\xee\xab\xb4"	// U+eaf4
#define ICON_CI_FOLD "\xee\xab\xb5"	// U+eaf5
#define ICON_CI_FOLDER_ACTIVE "\xee\xab\xb6"	// U+eaf6
#define ICON_CI_FOLDER_OPENED "\xee\xab\xb7"	// U+eaf7
#define ICON_CI_GEAR "\xee\xab\xb8"	// U+eaf8
#define ICON_CI_GIFT "\xee\xab\xb9"	// U+eaf9
#define ICON_CI_GIST_SECRET "\xee\xab\xba"	// U+eafa
#define ICON_CI_GIST "\xee\xab\xbb"	// U+eafb
#define ICON_CI_GIT_COMMIT "\xee\xab\xbc"	// U+eafc
#define ICON_CI_GIT_COMPARE "\xee\xab\xbd"	// U+eafd
#define ICON_CI_COMPARE_CHANGES "\xee\xab\xbd"	// U+eafd
#define ICON_CI_GIT_MERGE "\xee\xab\xbe"	// U+eafe
#define ICON_CI_GITHUB_ACTION "\xee\xab\xbf"	// U+eaff
#define ICON_CI_GITHUB_ALT "\xee\xac\x80"	// U+eb00
#define ICON_CI_GLOBE "\xee\xac\x81"	// U+eb01
#define ICON_CI_GRABBER "\xee\xac\x82"	// U+eb02
#define ICON_CI_GRAPH "\xee\xac\x83"	// U+eb03
#define ICON_CI_GRIPPER "\xee\xac\x84"	// U+eb04
#define ICON_CI_HEART "\xee\xac\x85"	// U+eb05
#define ICON_CI_HOME "\xee\xac\x86"	// U+eb06
#define ICON_CI_HORIZONTAL_RULE "\xee\xac\x87"	// U+eb07
#define ICON_CI_HUBOT "\xee\xac\x88"	// U+eb08
#define ICON_CI_INBOX "\xee\xac\x89"	// U+eb09
#define ICON_CI_ISSUE_REOPENED "\xee\xac\x8b"	// U+eb0b
#define ICON_CI_ISSUES "\xee\xac\x8c"	// U+eb0c
#define ICON_CI_ITALIC "\xee\xac\x8d"	// U+eb0d
#define ICON_CI_JERSEY "\xee\xac\x8e"	// U+eb0e
#define ICON_CI_JSON "\xee\xac\x8f"	// U+eb0f
#define ICON_CI_BRACKET "\xee\xac\x8f"	// U+eb0f
#define ICON_CI_KEBAB_VERTICAL "\xee\xac\x90"	// U+eb10
#define ICON_CI_KEY "\xee\xac\x91"	// U+eb11
#define ICON_CI_LAW "\xee\xac\x92"	// U+eb12
#define ICON_CI_LIGHTBULB_AUTOFIX "\xee\xac\x93"	// U+eb13
#define ICON_CI_LINK_EXTERNAL "\xee\xac\x94"	// U+eb14
#define ICON_CI_LINK "\xee\xac\x95"	// U+eb15
#define ICON_CI_LIST_ORDERED "\xee\xac\x96"	// U+eb16
#define ICON_CI_LIST_UNORDERED "\xee\xac\x97"	// U+eb17
#define ICON_CI_LIVE_SHARE "\xee\xac\x98"	// U+eb18
#define ICON_CI_LOADING "\xee\xac\x99"	// U+eb19
#define ICON_CI_LOCATION "\xee\xac\x9a"	// U+eb1a
#define ICON_CI_MAIL_READ "\xee\xac\x9b"	// U+eb1b
#define ICON_CI_MAIL "\xee\xac\x9c"	// U+eb1c
#define ICON_CI_MARKDOWN "\xee\xac\x9d"	// U+eb1d
#define ICON_CI_MEGAPHONE "\xee\xac\x9e"	// U+eb1e
#define ICON_CI_MENTION "\xee\xac\x9f"	// U+eb1f
#define ICON_CI_MILESTONE "\xee\xac\xa0"	// U+eb20
#define ICON_CI_GIT_PULL_REQUEST_MILESTONE "\xee\xac\xa0"	// U+eb20
#define ICON_CI_MORTAR_BOARD "\xee\xac\xa1"	// U+eb21
#define ICON_CI_MOVE "\xee\xac\xa2"	// U+eb22
#define ICON_CI_MULTIPLE_WINDOWS "\xee\xac\xa3"	// U+eb23
#define ICON_CI_MUTE "\xee\xac\xa4"	// U+eb24
#define ICON_CI_NO_NEWLINE "\xee\xac\xa5"	// U+eb25
#define ICON_CI_NOTE "\xee\xac\xa6"	// U+eb26
#define ICON_CI_OCTOFACE "\xee\xac\xa7"	// U+eb27
#define ICON_CI_OPEN_PREVIEW "\xee\xac\xa8"	// U+eb28
#define ICON_CI_PACKAGE "\xee\xac\xa9"	// U+eb29
#define ICON_CI_PAINTCAN "\xee\xac\xaa"	// U+eb2a
#define ICON_CI_PIN "\xee\xac\xab"	// U+eb2b
#define ICON_CI_PLAY "\xee\xac\xac"	// U+eb2c
#define ICON_CI_RUN "\xee\xac\xac"	// U+eb2c
#define ICON_CI_PLUG "\xee\xac\xad"	// U+eb2d
#define ICON_CI_PRESERVE_CASE "\xee\xac\xae"	// U+eb2e
#define ICON_CI_PREVIEW "\xee\xac\xaf"	// U+eb2f
#define ICON_CI_PROJECT "\xee\xac\xb0"	// U+eb30
#define ICON_CI_PULSE "\xee\xac\xb1"	// U+eb31
#define ICON_CI_QUESTION "\xee\xac\xb2"	// U+eb32
#define ICON_CI_QUOTE "\xee\xac\xb3"	// U+eb33
#define ICON_CI_RADIO_TOWER "\xee\xac\xb4"	// U+eb34
#define ICON_CI_REACTIONS "\xee\xac\xb5"	// U+eb35
#define ICON_CI_REFERENCES "\xee\xac\xb6"	// U+eb36
#define ICON_CI_REFRESH "\xee\xac\xb7"	// U+eb37
#define ICON_CI_REGEX "\xee\xac\xb8"	// U+eb38
#define ICON_CI_REMOTE_EXPLORER "\xee\xac\xb9"	// U+eb39
#define ICON_CI_REMOTE "\xee\xac\xba"	// U+eb3a
#define ICON_CI_REMOVE "\xee\xac\xbb"	// U+eb3b
#define ICON_CI_REPLACE_ALL "\xee\xac\xbc"	// U+eb3c
#define ICON_CI_REPLACE "\xee\xac\xbd"	// U+eb3d
#define ICON_CI_REPO_CLONE "\xee\xac\xbe"	// U+eb3e
#define ICON_CI_REPO_FORCE_PUSH "\xee\xac\xbf"	// U+eb3f
#define ICON_CI_REPO_PULL "\xee\xad\x80"	// U+eb40
#define ICON_CI_REPO_PUSH "\xee\xad\x81"	// U+eb41
#define ICON_CI_REPORT "\xee\xad\x82"	// U+eb42
#define ICON_CI_REQUEST_CHANGES "\xee\xad\x83"	// U+eb43
#define ICON_CI_ROCKET "\xee\xad\x84"	// U+eb44
#define ICON_CI_ROOT_FOLDER_OPENED "\xee\xad\x85"	// U+eb45
#define ICON_CI_ROOT_FOLDER "\xee\xad\x86"	// U+eb46
#define ICON_CI_RSS "\xee\xad\x87"	// U+eb47
#define ICON_CI_RUBY "\xee\xad\x88"	// U+eb48
#define ICON_CI_SAVE_ALL "\xee\xad\x89"	// U+eb49
#define ICON_CI_SAVE_AS "\xee\xad\x8a"	// U+eb4a
#define ICON_CI_SAVE "\xee\xad\x8b"	// U+eb4b
#define ICON_CI_SCREEN_FULL "\xee\xad\x8c"	// U+eb4c
#define ICON_CI_SCREEN_NORMAL "\xee\xad\x8d"	// U+eb4d
#define ICON_CI_SEARCH_STOP "\xee\xad\x8e"	// U+eb4e
#define ICON_CI_SERVER "\xee\xad\x90"	// U+eb50
#define ICON_CI_SETTINGS_GEAR "\xee\xad\x91"	// U+eb51
#define ICON_CI_SETTINGS "\xee\xad\x92"	// U+eb52
#define ICON_CI_SHIELD "\xee\xad\x93"	// U+eb53
#define ICON_CI_SMILEY "\xee\xad\x94"	// U+eb54
#define ICON_CI_SORT_PRECEDENCE "\xee\xad\x95"	// U+eb55
#define ICON_CI_SPLIT_HORIZONTAL "\xee\xad\x96"	// U+eb56
#define ICON_CI_SPLIT_VERTICAL "\xee\xad\x97"	// U+eb57
#define ICON_CI_SQUIRREL "\xee\xad\x98"	// U+eb58
#define ICON_CI_STAR_FULL "\xee\xad\x99"	// U+eb59
#define ICON_CI_STAR_HALF "\xee\xad\x9a"	// U+eb5a
#define ICON_CI_SYMBOL_CLASS "\xee\xad\x9b"	// U+eb5b
#define ICON_CI_SYMBOL_COLOR "\xee\xad\x9c"	// U+eb5c
#define ICON_CI_SYMBOL_CONSTANT "\xee\xad\x9d"	// U+eb5d
#define ICON_CI_SYMBOL_ENUM_MEMBER "\xee\xad\x9e"	// U+eb5e
#define ICON_CI_SYMBOL_FIELD "\xee\xad\x9f"	// U+eb5f
#define ICON_CI_SYMBOL_FILE "\xee\xad\xa0"	// U+eb60
#define ICON_CI_SYMBOL_INTERFACE "\xee\xad\xa1"	// U+eb61
#define ICON_CI_SYMBOL_KEYWORD "\xee\xad\xa2"	// U+eb62
#define ICON_CI_SYMBOL_MISC "\xee\xad\xa3"	// U+eb63
#define ICON_CI_SYMBOL_OPERATOR "\xee\xad\xa4"	// U+eb64
#define ICON_CI_SYMBOL_PROPERTY "\xee\xad\xa5"	// U+eb65
#define ICON_CI_WRENCH "\xee\xad\xa5"	// U+eb65
#define ICON_CI_WRENCH_SUBACTION "\xee\xad\xa5"	// U+eb65
#define ICON_CI_SYMBOL_SNIPPET "\xee\xad\xa6"	// U+eb66
#define ICON_CI_TASKLIST "\xee\xad\xa7"	// U+eb67
#define ICON_CI_TELESCOPE "\xee\xad\xa8"	// U+eb68
#define ICON_CI_TEXT_SIZE "\xee\xad\xa9"	// U+eb69
#define ICON_CI_THREE_BARS "\xee\xad\xaa"	// U+eb6a
#define ICON_CI_THUMBSDOWN "\xee\xad\xab"	// U+eb6b
#define ICON_CI_THUMBSUP "\xee\xad\xac"	// U+eb6c
#define ICON_CI_TOOLS "\xee\xad\xad"	// U+eb6d
#define ICON_CI_TRIANGLE_DOWN "\xee\xad\xae"	// U+eb6e
#define ICON_CI_TRIANGLE_LEFT "\xee\xad\xaf"	// U+eb6f
#define ICON_CI_TRIANGLE_RIGHT "\xee\xad\xb0"	// U+eb70
#define ICON_CI_TRIANGLE_UP "\xee\xad\xb1"	// U+eb71
#define ICON_CI_TWITTER "\xee\xad\xb2"	// U+eb72
#define ICON_CI_UNFOLD "\xee\xad\xb3"	// U+eb73
#define ICON_CI_UNLOCK "\xee\xad\xb4"	// U+eb74
#define ICON_CI_UNMUTE "\xee\xad\xb5"	// U+eb75
#define ICON_CI_UNVERIFIED "\xee\xad\xb6"	// U+eb76
#define ICON_CI_VERIFIED "\xee\xad\xb7"	// U+eb77
#define ICON_CI_VERSIONS "\xee\xad\xb8"	// U+eb78
#define ICON_CI_VM_ACTIVE "\xee\xad\xb9"	// U+eb79
#define ICON_CI_VM_OUTLINE "\xee\xad\xba"	// U+eb7a
#define ICON_CI_VM_RUNNING "\xee\xad\xbb"	// U+eb7b
#define ICON_CI_WATCH "\xee\xad\xbc"	// U+eb7c
#define ICON_CI_WHITESPACE "\xee\xad\xbd"	// U+eb7d
#define ICON_CI_WHOLE_WORD "\xee\xad\xbe"	// U+eb7e
#define ICON_CI_WINDOW "\xee\xad\xbf"	// U+eb7f
#define ICON_CI_WORD_WRAP "\xee\xae\x80"	// U+eb80
#define ICON_CI_ZOOM_IN "\xee\xae\x81"	// U+eb81
#define ICON_CI_ZOOM_OUT "\xee\xae\x82"	// U+eb82
#define ICON_CI_LIST_FILTER "\xee\xae\x83"	// U+eb83
#define ICON_CI_LIST_FLAT "\xee\xae\x84"	// U+eb84
#define ICON_CI_LIST_SELECTION "\xee\xae\x85"	// U+eb85
#define ICON_CI_SELECTION "\xee\xae\x85"	// U+eb85
#define ICON_CI_LIST_TREE "\xee\xae\x86"	// U+eb86
#define ICON_CI_DEBUG_BREAKPOINT_FUNCTION_UNVERIFIED "\xee\xae\x87"	// U+eb87
#define ICON_CI_DEBUG_BREAKPOINT_FUNCTION "\xee\xae\x88"	// U+eb88
#define ICON_CI_DEBUG_BREAKPOINT_FUNCTION_DISABLED "\xee\xae\x88"	// U+eb88
#define ICON_CI_DEBUG_STACKFRAME_ACTIVE "\xee\xae\x89"	// U+eb89
#define ICON_CI_CIRCLE_SMALL_FILLED "\xee\xae\x8a"	// U+eb8a
#define ICON_CI_DEBUG_STACKFRAME_DOT "\xee\xae\x8a"	// U+eb8a
#define ICON_CI_TERMINAL_DECORATION_MARK "\xee\xae\x8a"	// U+eb8a
#define ICON_CI_DEBUG_STACKFRAME "\xee\xae\x8b"	// U+eb8b
#define ICON_CI_DEBUG_STACKFRAME_FOCUSED "\xee\xae\x8b"	// U+eb8b
#define ICON_CI_DEBUG_BREAKPOINT_UNSUPPORTED "\xee\xae\x8c"	// U+eb8c
#define ICON_CI_SYMBOL_STRING "\xee\xae\x8d"	// U+eb8d
#define ICON_CI_DEBUG_REVERSE_CONTINUE "\xee\xae\x8e"	// U+eb8e
#define ICON_CI_DEBUG_STEP_BACK "\xee\xae\x8f"	// U+eb8f
#define ICON_CI_DEBUG_RESTART_FRAME "\xee\xae\x90"	// U+eb90
#define ICON_CI_DEBUG_ALT "\xee\xae\x91"	// U+eb91
#define ICON_CI_CALL_INCOMING "\xee\xae\x92"	// U+eb92
#define ICON_CI_CALL_OUTGOING "\xee\xae\x93"	// U+eb93
#define ICON_CI_MENU "\xee\xae\x94"	// U+eb94
#define ICON_CI_EXPAND_ALL "\xee\xae\x95"	// U+eb95
#define ICON_CI_FEEDBACK "\xee\xae\x96"	// U+eb96
#define ICON_CI_GIT_PULL_REQUEST_REVIEWER "\xee\xae\x96"	// U+eb96
#define ICON_CI_GROUP_BY_REF_TYPE "\xee\xae\x97"	// U+eb97
#define ICON_CI_UNGROUP_BY_REF_TYPE "\xee\xae\x98"	// U+eb98
#define ICON_CI_ACCOUNT "\xee\xae\x99"	// U+eb99
#define ICON_CI_GIT_PULL_REQUEST_ASSIGNEE "\xee\xae\x99"	// U+eb99
#define ICON_CI_BELL_DOT "\xee\xae\x9a"	// U+eb9a
#define ICON_CI_DEBUG_CONSOLE "\xee\xae\x9b"	// U+eb9b
#define ICON_CI_LIBRARY "\xee\xae\x9c"	// U+eb9c
#define ICON_CI_OUTPUT "\xee\xae\x9d"	// U+eb9d
#define ICON_CI_RUN_ALL "\xee\xae\x9e"	// U+eb9e
#define ICON_CI_SYNC_IGNORED "\xee\xae\x9f"	// U+eb9f
#define ICON_CI_PINNED "\xee\xae\xa0"	// U+eba0
#define ICON_CI_GITHUB_INVERTED "\xee\xae\xa1"	// U+eba1
#define ICON_CI_SERVER_PROCESS "\xee\xae\xa2"	// U+eba2
#define ICON_CI_SERVER_ENVIRONMENT "\xee\xae\xa3"	// U+eba3
#define ICON_CI_PASS "\xee\xae\xa4"	// U+eba4
#define ICON_CI_ISSUE_CLOSED "\xee\xae\xa4"	// U+eba4
#define ICON_CI_STOP_CIRCLE "\xee\xae\xa5"	// U+eba5
#define ICON_CI_PLAY_CIRCLE "\xee\xae\xa6"	// U+eba6
#define ICON_CI_RECORD "\xee\xae\xa7"	// U+eba7
#define ICON_CI_DEBUG_ALT_SMALL "\xee\xae\xa8"	// U+eba8
#define ICON_CI_VM_CONNECT "\xee\xae\xa9"	// U+eba9
#define ICON_CI_CLOUD "\xee\xae\xaa"	// U+ebaa
#define ICON_CI_MERGE "\xee\xae\xab"	// U+ebab
#define ICON_CI_EXPORT "\xee\xae\xac"	// U+ebac
#define ICON_CI_GRAPH_LEFT "\xee\xae\xad"	// U+ebad
#define ICON_CI_MAGNET "\xee\xae\xae"	// U+ebae
#define ICON_CI_NOTEBOOK "\xee\xae\xaf"	// U+ebaf
#define ICON_CI_REDO "\xee\xae\xb0"	// U+ebb0
#define ICON_CI_CHECK_ALL "\xee\xae\xb1"	// U+ebb1
#define ICON_CI_PINNED_DIRTY "\xee\xae\xb2"	// U+ebb2
#define ICON_CI_PASS_FILLED "\xee\xae\xb3"	// U+ebb3
#define ICON_CI_CIRCLE_LARGE_FILLED "\xee\xae\xb4"	// U+ebb4
#define ICON_CI_CIRCLE_LARGE "\xee\xae\xb5"	// U+ebb5
#define ICON_CI_CIRCLE_LARGE_OUTLINE "\xee\xae\xb5"	// U+ebb5
#define ICON_CI_COMBINE "\xee\xae\xb6"	// U+ebb6
#define ICON_CI_GATHER "\xee\xae\xb6"	// U+ebb6
#define ICON_CI_TABLE "\xee\xae\xb7"	// U+ebb7
#define ICON_CI_VARIABLE_GROUP "\xee\xae\xb8"	// U+ebb8
#define ICON_CI_TYPE_HIERARCHY "\xee\xae\xb9"	// U+ebb9
#define ICON_CI_TYPE_HIERARCHY_SUB "\xee\xae\xba"	// U+ebba
#define ICON_CI_TYPE_HIERARCHY_SUPER "\xee\xae\xbb"	// U+ebbb
#define ICON_CI_GIT_PULL_REQUEST_CREATE "\xee\xae\xbc"	// U+ebbc
#define ICON_CI_RUN_ABOVE "\xee\xae\xbd"	// U+ebbd
#define ICON_CI_RUN_BELOW "\xee\xae\xbe"	// U+ebbe
#define ICON_CI_NOTEBOOK_TEMPLATE "\xee\xae\xbf"	// U+ebbf
#define ICON_CI_DEBUG_RERUN "\xee\xaf\x80"	// U+ebc0
#define ICON_CI_WORKSPACE_TRUSTED "\xee\xaf\x81"	// U+ebc1
#define ICON_CI_WORKSPACE_UNTRUSTED "\xee\xaf\x82"	// U+ebc2
#define ICON_CI_WORKSPACE_UNKNOWN "\xee\xaf\x83"	// U+ebc3
#define ICON_CI_TERMINAL_CMD "\xee\xaf\x84"	// U+ebc4
#define ICON_CI_TERMINAL_DEBIAN "\xee\xaf\x85"	// U+ebc5
#define ICON_CI_TERMINAL_LINUX "\xee\xaf\x86"	// U+ebc6
#define ICON_CI_TERMINAL_POWERSHELL "\xee\xaf\x87"	// U+ebc7
#define ICON_CI_TERMINAL_TMUX "\xee\xaf\x88"	// U+ebc8
#define ICON_CI_TERMINAL_UBUNTU "\xee\xaf\x89"	// U+ebc9
#define ICON_CI_TERMINAL_BASH "\xee\xaf\x8a"	// U+ebca
#define ICON_CI_ARROW_SWAP "\xee\xaf\x8b"	// U+ebcb
#define ICON_CI_COPY "\xee\xaf\x8c"	// U+ebcc
#define ICON_CI_PERSON_ADD "\xee\xaf\x8d"	// U+ebcd
#define ICON_CI_FILTER_FILLED "\xee\xaf\x8e"	// U+ebce
#define ICON_CI_WAND "\xee\xaf\x8f"	// U+ebcf
#define ICON_CI_DEBUG_LINE_BY_LINE "\xee\xaf\x90"	// U+ebd0
#define ICON_CI_INSPECT "\xee\xaf\x91"	// U+ebd1
#define ICON_CI_LAYERS "\xee\xaf\x92"	// U+ebd2
#define ICON_CI_LAYERS_DOT "\xee\xaf\x93"	// U+ebd3
#define ICON_CI_LAYERS_ACTIVE "\xee\xaf\x94"	// U+ebd4
#define ICON_CI_COMPASS "\xee\xaf\x95"	// U+ebd5
#define ICON_CI_COMPASS_DOT "\xee\xaf\x96"	// U+ebd6
#define ICON_CI_COMPASS_ACTIVE "\xee\xaf\x97"	// U+ebd7
#define ICON_CI_AZURE "\xee\xaf\x98"	// U+ebd8
#define ICON_CI_ISSUE_DRAFT "\xee\xaf\x99"	// U+ebd9
#define ICON_CI_GIT_PULL_REQUEST_CLOSED "\xee\xaf\x9a"	// U+ebda
#define ICON_CI_GIT_PULL_REQUEST_DRAFT "\xee\xaf\x9b"	// U+ebdb
#define ICON_CI_DEBUG_ALL "\xee\xaf\x9c"	// U+ebdc
#define ICON_CI_DEBUG_COVERAGE "\xee\xaf\x9d"	// U+ebdd
#define ICON_CI_RUN_ERRORS "\xee\xaf\x9e"	// U+ebde
#define ICON_CI_FOLDER_LIBRARY "\xee\xaf\x9f"	// U+ebdf
#define ICON_CI_DEBUG_CONTINUE_SMALL "\xee\xaf\xa0"	// U+ebe0
#define ICON_CI_BEAKER_STOP "\xee\xaf\xa1"	// U+ebe1
#define ICON_CI_GRAPH_LINE "\xee\xaf\xa2"	// U+ebe2
#define ICON_CI_GRAPH_SCATTER "\xee\xaf\xa3"	// U+ebe3
#define ICON_CI_PIE_CHART "\xee\xaf\xa4"	// U+ebe4
#define ICON_CI_BRACKET_DOT "\xee\xaf\xa5"	// U+ebe5
#define ICON_CI_BRACKET_ERROR "\xee\xaf\xa6"	// U+ebe6
#define ICON_CI_LOCK_SMALL "\xee\xaf\xa7"	// U+ebe7
#define ICON_CI_AZURE_DEVOPS "\xee\xaf\xa8"	// U+ebe8
#define ICON_CI_VERIFIED_FILLED "\xee\xaf\xa9"	// U+ebe9
#define ICON_CI_NEWLINE "\xee\xaf\xaa"	// U+ebea
#define ICON_CI_LAYOUT "\xee\xaf\xab"	// U+ebeb
#define ICON_CI_LAYOUT_ACTIVITYBAR_LEFT "\xee\xaf\xac"	// U+ebec
#define ICON_CI_LAYOUT_ACTIVITYBAR_RIGHT "\xee\xaf\xad"	// U+ebed
#define ICON_CI_LAYOUT_PANEL_LEFT "\xee\xaf\xae"	// U+ebee
#define ICON_CI_LAYOUT_PANEL_CENTER "\xee\xaf\xaf"	// U+ebef
#define ICON_CI_LAYOUT_PANEL_JUSTIFY "\xee\xaf\xb0"	// U+ebf0
#define ICON_CI_LAYOUT_PANEL_RIGHT "\xee\xaf\xb1"	// U+ebf1
#define ICON_CI_LAYOUT_PANEL "\xee\xaf\xb2"	// U+ebf2
#define ICON_CI_LAYOUT_SIDEBAR_LEFT "\xee\xaf\xb3"	// U+ebf3
#define ICON_CI_LAYOUT_SIDEBAR_RIGHT "\xee\xaf\xb4"	// U+ebf4
#define ICON_CI_LAYOUT_STATUSBAR "\xee\xaf\xb5"	// U+ebf5
#define ICON_CI_LAYOUT_MENUBAR "\xee\xaf\xb6"	// U+ebf6
#define ICON_CI_LAYOUT_CENTERED "\xee\xaf\xb7"	// U+ebf7
#define ICON_CI_TARGET "\xee\xaf\xb8"	// U+ebf8
#define ICON_CI_INDENT "\xee\xaf\xb9"	// U+ebf9
#define ICON_CI_RECORD_SMALL "\xee\xaf\xba"	// U+ebfa
#define ICON_CI_ERROR_SMALL "\xee\xaf\xbb"	// U+ebfb
#define ICON_CI_TERMINAL_DECORATION_ERROR "\xee\xaf\xbb"	// U+ebfb
#define ICON_CI_ARROW_CIRCLE_DOWN "\xee\xaf\xbc"	// U+ebfc
#define ICON_CI_ARROW_CIRCLE_LEFT "\xee\xaf\xbd"	// U+ebfd
#define ICON_CI_ARROW_CIRCLE_RIGHT "\xee\xaf\xbe"	// U+ebfe
#define ICON_CI_ARROW_CIRCLE_UP "\xee\xaf\xbf"	// U+ebff
#define ICON_CI_LAYOUT_SIDEBAR_RIGHT_OFF "\xee\xb0\x80"	// U+ec00
#define ICON_CI_LAYOUT_PANEL_OFF "\xee\xb0\x81"	// U+ec01
#define ICON_CI_LAYOUT_SIDEBAR_LEFT_OFF "\xee\xb0\x82"	// U+ec02
#define ICON_CI_BLANK "\xee\xb0\x83"	// U+ec03
#define ICON_CI_HEART_FILLED "\xee\xb0\x84"	// U+ec04
#define ICON_CI_MAP "\xee\xb0\x85"	// U+ec05
#define ICON_CI_MAP_HORIZONTAL "\xee\xb0\x85"	// U+ec05
#define ICON_CI_FOLD_HORIZONTAL "\xee\xb0\x85"	// U+ec05
#define ICON_CI_MAP_FILLED "\xee\xb0\x86"	// U+ec06
#define ICON_CI_MAP_HORIZONTAL_FILLED "\xee\xb0\x86"	// U+ec06
#define ICON_CI_FOLD_HORIZONTAL_FILLED "\xee\xb0\x86"	// U+ec06
#define ICON_CI_CIRCLE_SMALL "\xee\xb0\x87"	// U+ec07
#define ICON_CI_BELL_SLASH "\xee\xb0\x88"	// U+ec08
#define ICON_CI_BELL_SLASH_DOT "\xee\xb0\x89"	// U+ec09
#define ICON_CI_COMMENT_UNRESOLVED "\xee\xb0\x8a"	// U+ec0a
#define ICON_CI_GIT_PULL_REQUEST_GO_TO_CHANGES "\xee\xb0\x8b"	// U+ec0b
#define ICON_CI_GIT_PULL_REQUEST_NEW_CHANGES "\xee\xb0\x8c"	// U+ec0c
#define ICON_CI_SEARCH_FUZZY "\xee\xb0\x8d"	// U+ec0d
#define ICON_CI_COMMENT_DRAFT "\xee\xb0\x8e"	// U+ec0e
#define ICON_CI_SEND "\xee\xb0\x8f"	// U+ec0f
#define ICON_CI_SPARKLE "\xee\xb0\x90"	// U+ec10
#define ICON_CI_INSERT "\xee\xb0\x91"	// U+ec11
#define ICON_CI_MIC "\xee\xb0\x92"	// U+ec12
#define ICON_CI_THUMBSDOWN_FILLED "\xee\xb0\x93"	// U+ec13
#define ICON_CI_THUMBSUP_FILLED "\xee\xb0\x94"	// U+ec14
#define ICON_CI_COFFEE "\xee\xb0\x95"	// U+ec15
#define ICON_CI_SNAKE "\xee\xb0\x96"	// U+ec16
#define ICON_CI_GAME "\xee\xb0\x97"	// U+ec17
#define ICON_CI_VR "\xee\xb0\x98"	// U+ec18
#define ICON_CI_CHIP "\xee\xb0\x99"	// U+ec19
#define ICON_CI_PIANO "\xee\xb0\x9a"	// U+ec1a
#define ICON_CI_MUSIC "\xee\xb0\x9b"	// U+ec1b
#define ICON_CI_MIC_FILLED "\xee\xb0\x9c"	// U+ec1c
#define ICON_CI_REPO_FETCH "\xee\xb0\x9d"	// U+ec1d
#define ICON_CI_COPILOT "\xee\xb0\x9e"	// U+ec1e
#define ICON_CI_LIGHTBULB_SPARKLE "\xee\xb0\x9f"	// U+ec1f
#define ICON_CI_ROBOT "\xee\xb0\xa0"	// U+ec20
#define ICON_CI_SPARKLE_FILLED "\xee\xb0\xa1"	// U+ec21
#define ICON_CI_DIFF_SINGLE "\xee\xb0\xa2"	// U+ec22
#define ICON_CI_DIFF_MULTIPLE "\xee\xb0\xa3"	// U+ec23
#define ICON_CI_SURROUND_WITH "\xee\xb0\xa4"	// U+ec24
#define ICON_CI_SHARE "\xee\xb0\xa5"	// U+ec25
#define ICON_CI_GIT_STASH "\xee\xb0\xa6"	// U+ec26
#define ICON_CI_GIT_STASH_APPLY "\xee\xb0\xa7"	// U+ec27
#define ICON_CI_GIT_STASH_POP "\xee\xb0\xa8"	// U+ec28
#define ICON_CI_VSCODE "\xee\xb0\xa9"	// U+ec29
#define ICON_CI_VSCODE_INSIDERS "\xee\xb0\xaa"	// U+ec2a
#define ICON_CI_CODE_OSS "\xee\xb0\xab"	// U+ec2b
#define ICON_CI_RUN_COVERAGE "\xee\xb0\xac"	// U+ec2c
#define ICON_CI_RUN_ALL_COVERAGE "\xee\xb0\xad"	// U+ec2d
#define ICON_CI_COVERAGE "\xee\xb0\xae"	// U+ec2e
#define ICON_CI_GITHUB_PROJECT "\xee\xb0\xaf"	// U+ec2f
#define ICON_CI_MAP_VERTICAL "\xee\xb0\xb0"	// U+ec30
#define ICON_CI_FOLD_VERTICAL "\xee\xb0\xb0"	// U+ec30
#define ICON_CI_MAP_VERTICAL_FILLED "\xee\xb0\xb1"	// U+ec31
#define ICON_CI_FOLD_VERTICAL_FILLED "\xee\xb0\xb1"	// U+ec31
#define ICON_CI_GO_TO_SEARCH "\xee\xb0\xb2"	// U+ec32
#define ICON_CI_PERCENTAGE "\xee\xb0\xb3"	// U+ec33
#define ICON_CI_SORT_PERCENTAGE "\xee\xb0\xb3"	// U+ec33
#define ICON_CI_ATTACH "\xee\xb0\xb4"	// U+ec34
#define ICON_CI_GO_TO_EDITING_SESSION "\xee\xb0\xb5"	// U+ec35
#define ICON_CI_EDIT_SESSION "\xee\xb0\xb6"	// U+ec36
#define ICON_CI_CODE_REVIEW "\xee\xb0\xb7"	// U+ec37
#define ICON_CI_COPILOT_WARNING "\xee\xb0\xb8"	// U+ec38
#define ICON_CI_PYTHON "\xee\xb0\xb9"	// U+ec39
#define ICON_CI_COPILOT_LARGE "\xee\xb0\xba"	// U+ec3a
#define ICON_CI_COPILOT_WARNING_LARGE "\xee\xb0\xbb"	// U+ec3b
#define ICON_CI_KEYBOARD_TAB "\xee\xb0\xbc"	// U+ec3c
#define ICON_CI_COPILOT_BLOCKED "\xee\xb0\xbd"	// U+ec3d
#define ICON_CI_COPILOT_NOT_CONNECTED "\xee\xb0\xbe"	// U+ec3e
#define ICON_CI_FLAG "\xee\xb0\xbf"	// U+ec3f
#define ICON_CI_LIGHTBULB_EMPTY "\xee\xb1\x80"	// U+ec40
#define ICON_CI_SYMBOL_METHOD_ARROW "\xee\xb1\x81"	// U+ec41
#define ICON_CI_COPILOT_UNAVAILABLE "\xee\xb1\x82"	// U+ec42
#define ICON_CI_REPO_PINNED "\xee\xb1\x83"	// U+ec43
#define ICON_CI_KEYBOARD_TAB_ABOVE "\xee\xb1\x84"	// U+ec44
#define ICON_CI_KEYBOARD_TAB_BELOW "\xee\xb1\x85"	// U+ec45
#define ICON_CI_GIT_PULL_REQUEST_DONE "\xee\xb1\x86"	// U+ec46
#define ICON_CI_MCP "\xee\xb1\x87"	// U+ec47
#define ICON_CI_EXTENSIONS_LARGE "\xee\xb1\x88"	// U+ec48
#define ICON_CI_LAYOUT_PANEL_DOCK "\xee\xb1\x89"	// U+ec49
#define ICON_CI_LAYOUT_SIDEBAR_LEFT_DOCK "\xee\xb1\x8a"	// U+ec4a
#define ICON_CI_LAYOUT_SIDEBAR_RIGHT_DOCK "\xee\xb1\x8b"	// U+ec4b
#define ICON_CI_COPILOT_IN_PROGRESS "\xee\xb1\x8c"	// U+ec4c
#define ICON_CI_COPILOT_ERROR "\xee\xb1\x8d"	// U+ec4d
#define ICON_CI_COPILOT_SUCCESS "\xee\xb1\x8e"	// U+ec4e
#define ICON_CI_CHAT_SPARKLE "\xee\xb1\x8f"	// U+ec4f
#define ICON_CI_SEARCH_SPARKLE "\xee\xb1\x90"	// U+ec50
#define ICON_CI_EDIT_SPARKLE "\xee\xb1\x91"	// U+ec51
#define ICON_CI_COPILOT_SNOOZE "\xee\xb1\x92"	// U+ec52
#define ICON_CI_SEND_TO_REMOTE_AGENT "\xee\xb1\x93"	// U+ec53
#define ICON_CI_COMMENT_DISCUSSION_SPARKLE "\xee\xb1\x94"	// U+ec54
#define ICON_CI_CHAT_SPARKLE_WARNING "\xee\xb1\x95"	// U+ec55
#define ICON_CI_CHAT_SPARKLE_ERROR "\xee\xb1\x96"	// U+ec56
#define ICON_CI_COLLECTION "\xee\xb1\x97"	// U+ec57
#define ICON_CI_NEW_COLLECTION "\xee\xb1\x98"	// U+ec58
#define ICON_CI_THINKING "\xee\xb1\x99"	// U+ec59
#define ICON_CI_BUILD "\xee\xb1\x9a"	// U+ec5a
#define ICON_CI_COMMENT_DISCUSSION_QUOTE "\xee\xb1\x9b"	// U+ec5b
#define ICON_CI_CURSOR "\xee\xb1\x9c"	// U+ec5c
#define ICON_CI_ERASER "\xee\xb1\x9d"	// U+ec5d
#define ICON_CI_FILE_TEXT "\xee\xb1\x9e"	// U+ec5e
#define ICON_CI_QUOTES "\xee\xb1\xa0"	// U+ec60
#define ICON_CI_RENAME "\xee\xb1\xa1"	// U+ec61
#define ICON_CI_RUN_WITH_DEPS "\xee\xb1\xa2"	// U+ec62
#define ICON_CI_DEBUG_CONNECTED "\xee\xb1\xa3"	// U+ec63
#define ICON_CI_STRIKETHROUGH "\xee\xb1\xa4"	// U+ec64
#define ICON_CI_OPEN_IN_PRODUCT "\xee\xb1\xa5"	// U+ec65
#define ICON_CI_INDEX_ZERO "\xee\xb1\xa6"	// U+ec66
#define ICON_CI_AGENT "\xee\xb1\xa7"	// U+ec67
#define ICON_CI_EDIT_CODE "\xee\xb1\xa8"	// U+ec68
#define ICON_CI_REPO_SELECTED "\xee\xb1\xa9"	// U+ec69
#define ICON_CI_SKIP "\xee\xb1\xaa"	// U+ec6a
#define ICON_CI_MERGE_INTO "\xee\xb1\xab"	// U+ec6b
#define ICON_CI_GIT_BRANCH_CHANGES "\xee\xb1\xac"	// U+ec6c
#define ICON_CI_GIT_BRANCH_STAGED_CHANGES "\xee\xb1\xad"	// U+ec6d
#define ICON_CI_GIT_BRANCH_CONFLICTS "\xee\xb1\xae"	// U+ec6e
#define ICON_CI_GIT_BRANCH "\xee\xb1\xaf"	// U+ec6f
#define ICON_CI_GIT_BRANCH_CREATE "\xee\xb1\xaf"	// U+ec6f
#define ICON_CI_GIT_BRANCH_DELETE "\xee\xb1\xaf"	// U+ec6f
#define ICON_CI_SEARCH_LARGE "\xee\xb1\xb0"	// U+ec70
#define ICON_CI_TERMINAL_GIT_BASH "\xee\xb1\xb1"	// U+ec71
#define ICON_CI_WINDOW_ACTIVE "\xee\xb1\xb2"	// U+ec72
#define ICON_CI_FORWARD "\xee\xb1\xb3"	// U+ec73
#define ICON_CI_DOWNLOAD "\xee\xb1\xb4"	// U+ec74
#define ICON_CI_CLOCKFACE "\xee\xb1\xb5"	// U+ec75
#define ICON_CI_UNARCHIVE "\xee\xb1\xb6"	// U+ec76
#define ICON_CI_SESSION_IN_PROGRESS "\xee\xb1\xb7"	// U+ec77
#define ICON_CI_COLLECTION_SMALL "\xee\xb1\xb8"	// U+ec78
#define ICON_CI_VM_SMALL "\xee\xb1\xb9"	// U+ec79
#define ICON_CI_CLOUD_SMALL "\xee\xb1\xba"	// U+ec7a
#define ICON_CI_ADD_SMALL "\xee\xb1\xbb"	// U+ec7b
#define ICON_CI_REMOVE_SMALL "\xee\xb1\xbc"	// U+ec7c
#define ICON_CI_WORKTREE_SMALL "\xee\xb1\xbd"	// U+ec7d
#define ICON_CI_WORKTREE "\xee\xb1\xbe"	// U+ec7e
#define ICON_CI_SCREEN_CUT "\xee\xb1\xbf"	// U+ec7f
#define ICON_CI_ASK "\xee\xb2\x80"	// U+ec80
#define ICON_CI_OPENAI "\xee\xb2\x81"	// U+ec81
#define ICON_CI_CLAUDE "\xee\xb2\x82"	// U+ec82
#define ICON_CI_OPEN_IN_WINDOW "\xee\xb2\x83"	// U+ec83
#define ICON_CI_NEW_SESSION "\xee\xb2\x84"	// U+ec84
#define ICON_CI_TERMINAL_SECURE "\xee\xb2\x85"	// U+ec85
#define ICON_CI_CHAT_IMPORT "\xee\xb2\x86"	// U+ec86
#define ICON_CI_CHAT_EXPORT "\xee\xb2\x87"	// U+ec87
#define ICON_CI_SHARE_WINDOW "\xee\xb2\x88"	// U+ec88
#define ICON_CI_CIRCLE_SLASH_COMPACT "\xee\xb2\x89"	// U+ec89
#define ICON_CI_COPILOT_COMPACT "\xee\xb2\x8a"	// U+ec8a
#define ICON_CI_FOLDER_OPENED_COMPACT "\xee\xb2\x8b"	// U+ec8b
#define ICON_CI_FOLDER_COMPACT "\xee\xb2\x8c"	// U+ec8c
#define ICON_CI_GEAR_COMPACT "\xee\xb2\x8d"	// U+ec8d
#define ICON_CI_GIT_BRANCH_COMPACT "\xee\xb2\x8e"	// U+ec8e
#define ICON_CI_LIBRARY_COMPACT "\xee\xb2\x8f"	// U+ec8f
#define ICON_CI_RECORD_KEYS_COMPACT "\xee\xb2\x90"	// U+ec90
#define ICON_CI_REMOTE_COMPACT "\xee\xb2\x91"	// U+ec91
#define ICON_CI_REPO_FORKED_COMPACT "\xee\xb2\x92"	// U+ec92
#define ICON_CI_REPO_COMPACT "\xee\xb2\x93"	// U+ec93
#define ICON_CI_SHIELD_COMPACT "\xee\xb2\x94"	// U+ec94
#define ICON_CI_SPARKLE_COMPACT "\xee\xb2\x95"	// U+ec95
#define ICON_CI_SYMBOL_COLOR_COMPACT "\xee\xb2\x96"	// U+ec96
#define ICON_CI_WINDOW_COMPACT "\xee\xb2\x97"	// U+ec97
#define ICON_CI_ERROR_COMPACT "\xee\xb2\x98"	// U+ec98
#define ICON_CI_WARNING_COMPACT "\xee\xb2\x99"	// U+ec99
#define ICON_CI_PASS_COMPACT "\xee\xb2\x9a"	// U+ec9a
#define ICON_CI_IMPORTANT "\xee\xb2\x9b"	// U+ec9b
#define ICON_CI_IMPORTANT_COMPACT "\xee\xb2\x9c"	// U+ec9c
#define ICON_CI_ROCKET_COMPACT "\xee\xb2\x9d"	// U+ec9d
#define ICON_CI_UNPIN "\xee\xb2\x9e"	// U+ec9e
#define ICON_CI_ADD_COMPACT "\xee\xb2\x9f"	// U+ec9f
#define ICON_CI_ATTACH_COMPACT "\xee\xb2\xa0"	// U+eca0
#define ICON_CI_BEAKER_COMPACT "\xee\xb2\xa1"	// U+eca1
#define ICON_CI_CHECK_COMPACT "\xee\xb2\xa2"	// U+eca2
#define ICON_CI_CHECKLIST_COMPACT "\xee\xb2\xa3"	// U+eca3
#define ICON_CI_CHEVRON_DOWN_COMPACT "\xee\xb2\xa4"	// U+eca4
#define ICON_CI_CHEVRON_LEFT_COMPACT "\xee\xb2\xa5"	// U+eca5
#define ICON_CI_CHEVRON_RIGHT_COMPACT "\xee\xb2\xa6"	// U+eca6
#define ICON_CI_CHEVRON_UP_COMPACT "\xee\xb2\xa7"	// U+eca7
#define ICON_CI_CIRCLE_FILLED_COMPACT "\xee\xb2\xa8"	// U+eca8
#define ICON_CI_CIRCLE_SMALL_FILLED_COMPACT "\xee\xb2\xa9"	// U+eca9
#define ICON_CI_CLOSE_COMPACT "\xee\xb2\xaa"	// U+ecaa
#define ICON_CI_COLLAPSE_ALL_COMPACT "\xee\xb2\xab"	// U+ecab
#define ICON_CI_COMMENT_COMPACT "\xee\xb2\xac"	// U+ecac
#define ICON_CI_COMMENT_UNRESOLVED_COMPACT "\xee\xb2\xad"	// U+ecad
#define ICON_CI_DEBUG_CONNECTED_COMPACT "\xee\xb2\xae"	// U+ecae
#define ICON_CI_DEBUG_DISCONNECT_COMPACT "\xee\xb2\xaf"	// U+ecaf
#define ICON_CI_EDIT_COMPACT "\xee\xb2\xb0"	// U+ecb0
#define ICON_CI_FILE_MEDIA_COMPACT "\xee\xb2\xb1"	// U+ecb1
#define ICON_CI_GIT_FETCH "\xee\xb2\xb2"	// U+ecb2
#define ICON_CI_LIGHTBULB_COMPACT "\xee\xb2\xb3"	// U+ecb3
#define ICON_CI_LOADING_COMPACT "\xee\xb2\xb4"	// U+ecb4
#define ICON_CI_PASS_FILLED_COMPACT "\xee\xb2\xb5"	// U+ecb5
#define ICON_CI_PROJECT_COMPACT "\xee\xb2\xb6"	// U+ecb6
#define ICON_CI_REFRESH_COMPACT "\xee\xb2\xb7"	// U+ecb7
#define ICON_CI_SEARCH_COMPACT "\xee\xb2\xb8"	// U+ecb8
#define ICON_CI_SESSION_IN_PROGRESS_COMPACT "\xee\xb2\xb9"	// U+ecb9
#define ICON_CI_SYNC_COMPACT "\xee\xb2\xba"	// U+ecba
#define ICON_CI_TERMINAL_COMPACT "\xee\xb2\xbb"	// U+ecbb
#define ICON_CI_VM_PENDING "\xee\xb2\xbc"	// U+ecbc
#define ICON_CI_WORKTREE_COMPACT "\xee\xb2\xbd"	// U+ecbd
#define ICON_CI_DEVELOPER_TOOLS "\xee\xb2\xbe"	// U+ecbe
#define ICON_CI_CLOUD_COMPACT "\xee\xb2\xbf"	// U+ecbf
#define ICON_CI_AGENT_COMPACT "\xee\xb3\x80"	// U+ecc0
#define ICON_CI_ASK_COMPACT "\xee\xb3\x81"	// U+ecc1
#define ICON_CI_SETTINGS_COMPACT "\xee\xb3\x82"	// U+ecc2
#define ICON_CI_VM_COMPACT "\xee\xb3\x83"	// U+ecc3

#pragma endregion