#pragma once

#include "Asset.h"
#include "Renderer/GPUBuffers.h"
#include "Renderer/BVH.h"
#include "Renderer/Skeleton.h"
#include <glm/vec2.hpp>
#include <glm/vec3.hpp>
#include <glm/vec4.hpp>
#include <unordered_map>

namespace Fufu
{
	struct Vertex
	{
		glm::vec3 position;
		glm::vec3 normal;
		glm::vec2 uv;
		glm::vec3 tangent;
		// Skinning (zero-initialized; only populated when mesh has bones)
		glm::ivec4 boneIndices{0, 0, 0, 0};
		glm::vec4  boneWeights{0.f, 0.f, 0.f, 0.f};
	};

	struct SubMesh
	{
		std::vector<Vertex> vertices;
		std::vector<uint32_t> indices;
		std::string name;
	};

	// BLAS for one LOD level: geometry (local space, all sub-meshes concatenated)
	// + BVH built on top of it. Cached by MeshAsset (see getOrBuildBLAS) —
	// built once, not every frame the mesh is referenced by a scene.
	// Geometry is already split into two buffers at the cache level: positions
	// (read during BVH traversal) and attributes (read once, on the final hit —
	// see GPUTrianglePosition/GPUTriangleAttribute).
	struct MeshBLAS
	{
		std::vector<GPUTrianglePosition>  positions;
		std::vector<GPUTriangleAttribute> attributes;
		std::vector<GPUBVHNode>           nodes;
		// Non-empty when mesh has bones: skin weights in BVH leaf order,
		// parallel to positions[]. Used by GPUScene::updateSkinning().
		std::vector<GPUSkinTriangle>      skinWeights;
	};

	class MeshAsset : public Asset
	{
	public:
		AssetType getType() const override { return AssetType::Mesh; }

		const std::vector<SubMesh>& getSubMeshes() const { return m_SubMeshes; }
		size_t getSubMeshCount() const { return m_SubMeshes.size(); }

		// Mutable access for mesh editing tools (see ModelingTool / SculptTool
		// on the editor side). The Renderer re-uploads the scene every frame,
		// so any modification here is immediately visible.
		// Always the full detail level (LOD0) — editing tools never operate
		// on a simplified LOD.
		std::vector<SubMesh>& getSubMeshesMutable() { return m_SubMeshes; }

		// LOD: level 0 = full detail (identical to getSubMeshes()). Subsequent
		// levels are lazily generated by vertex clustering (see MeshSimplifier)
		// and cached — the first call with level>0 has a cost, subsequent calls
		// are free until invalidateLODs(). A level requested beyond the last
		// generated one falls back to the most simplified available.
		static constexpr int k_ExtraLODLevels = 2; // en plus de LOD0
		const std::vector<SubMesh>& getLODSubMeshes(int level) const;

		// To be called after any edit to LOD0 (sculpt, extrude...): generated
		// LODs become stale and will be rebuilt on demand. Also invalidates
		// the BLAS cache (getOrBuildBLAS) since it derives directly from the
		// sub-meshes.
		void invalidateLODs()
		{
			m_LODLevels.clear();
			m_LODsGenerated = false;
			m_BLASCache.clear();
			++m_BLASVersion;
		}

		// BLAS (triangles + BVH) for the requested LOD level, built once and
		// then cached — it is THIS cache, not GPUScene, that decides when a BVH
		// must be rebuilt. Moving an entity that references this mesh never
		// touches it: only invalidateLODs() (sculpt, extrude, mesh change) does.
		const MeshBLAS& getOrBuildBLAS(int lod) const;

		// Incremented each time a BLAS (any LOD) is (re)built — serves as a
		// signature for GPUScene to know whether its concatenated GPU buffers
		// are still up to date, without comparing content.
		uint64_t getBLASVersion() const { return m_BLASVersion; }

		// Skeletal animation
		bool hasBones() const { return m_HasBones; }
		const Skeleton&                   getSkeleton()        const { return m_Skeleton; }
		const std::vector<AnimationClip>& getAnimationClips()  const { return m_AnimationClips; }

	private:
		void ensureLODsGenerated() const;

		std::vector<SubMesh> m_SubMeshes; // LOD0

		mutable std::vector<std::vector<SubMesh>> m_LODLevels; // LOD1, LOD2, ...
		mutable bool m_LODsGenerated = false;

		mutable std::unordered_map<int, MeshBLAS> m_BLASCache; // per LOD level
		mutable uint64_t m_BLASVersion = 0;

		bool                       m_HasBones = false;
		Skeleton                   m_Skeleton;
		std::vector<AnimationClip> m_AnimationClips;

		friend class AssetManager;
	};
}
